# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_2/system_processing_system7_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_2 || ORIG_REF_NAME==system_processing_system7_0_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_3/system_axi_smc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_smc_3 || ORIG_REF_NAME==system_axi_smc_3} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_100M_3/system_rst_ps7_0_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_3 || ORIG_REF_NAME==system_rst_ps7_0_100M_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_xbar_2/system_axi_mem_intercon_imp_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_xbar_2 || ORIG_REF_NAME==system_axi_mem_intercon_imp_xbar_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_3/system_axi_mem_intercon_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_3 || ORIG_REF_NAME==system_axi_mem_intercon_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_us_0/system_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_us_1/system_axi_mem_intercon_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_us_1 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_us_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_us_2/system_axi_mem_intercon_imp_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_us_2 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_us_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_pc_0/system_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_conv2d_0_10/system_conv2d_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_conv2d_0_10 || ORIG_REF_NAME==system_conv2d_0_10} -quiet] -quiet

# XDC: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.gen/sources_1/bd/system/system_ooc.xdc
