// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module conv2d_conv2d_Pipeline_VITIS_LOOP_137_22_VITIS_LOOP_138_23_VITIS_LOOP_139_24 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool2_out_address0,
        pool2_out_ce0,
        pool2_out_q0,
        fc_in_address0,
        fc_in_ce0,
        fc_in_we0,
        fc_in_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] pool2_out_address0;
output   pool2_out_ce0;
input  [31:0] pool2_out_q0;
output  [8:0] fc_in_address0;
output   fc_in_ce0;
output   fc_in_we0;
output  [31:0] fc_in_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln137_fu_168_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln138_fu_183_p2;
reg   [0:0] icmp_ln138_reg_543;
reg   [0:0] icmp_ln138_reg_543_pp0_iter1_reg;
reg   [0:0] icmp_ln138_reg_543_pp0_iter2_reg;
wire   [0:0] and_ln137_fu_246_p2;
reg   [0:0] and_ln137_reg_554;
reg   [0:0] and_ln137_reg_554_pp0_iter2_reg;
wire   [2:0] j_4_mid2_fu_270_p3;
reg   [2:0] j_4_mid2_reg_560;
wire   [7:0] add_ln140_1_fu_312_p2;
reg   [7:0] add_ln140_1_reg_565;
wire   [6:0] trunc_ln140_fu_318_p1;
reg   [6:0] trunc_ln140_reg_570;
wire   [63:0] zext_ln140_4_fu_368_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln139_1_fu_423_p1;
reg   [2:0] j_fu_58;
wire   [2:0] add_ln139_1_fu_322_p2;
wire    ap_loop_init;
reg   [8:0] idx_1_fu_62;
wire   [8:0] add_ln140_fu_428_p2;
reg   [8:0] add_ln137_11_fu_66;
wire   [8:0] add_ln137_1_fu_440_p2;
reg   [8:0] idx_fu_70;
wire   [8:0] select_ln138_fu_416_p3;
reg   [8:0] add_ln1393_fu_74;
wire   [8:0] add_ln139_fu_434_p2;
reg   [2:0] i_fu_78;
wire   [2:0] select_ln138_1_fu_278_p3;
reg   [5:0] indvar_flatten133_fu_82;
wire   [5:0] select_ln138_2_fu_195_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten133_load;
reg   [4:0] c_fu_86;
wire   [4:0] select_ln137_4_fu_252_p3;
reg   [8:0] indvars_iv172_fu_90;
wire   [8:0] select_ln137_3_fu_402_p3;
reg   [8:0] indvar_flatten151_fu_94;
wire   [8:0] add_ln137_2_fu_174_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten151_load;
reg    pool2_out_ce0_local;
reg    fc_in_we0_local;
reg    fc_in_ce0_local;
wire   [5:0] add_ln138_1_fu_189_p2;
wire   [0:0] icmp_ln139_fu_240_p2;
wire   [0:0] xor_ln137_fu_235_p2;
wire   [4:0] add_ln137_fu_222_p2;
wire   [2:0] select_ln137_1_fu_228_p3;
wire   [0:0] empty_fu_265_p2;
wire   [2:0] add_ln138_fu_259_p2;
wire   [6:0] tmp_fu_290_p3;
wire   [7:0] zext_ln140_1_fu_298_p1;
wire   [7:0] zext_ln140_fu_286_p1;
wire   [7:0] add_ln140_3_fu_302_p2;
wire   [7:0] zext_ln140_2_fu_308_p1;
wire   [8:0] p_shl_fu_346_p3;
wire   [8:0] zext_ln139_fu_343_p1;
wire   [8:0] add_ln139_2_fu_353_p2;
wire   [8:0] zext_ln140_3_fu_359_p1;
wire   [8:0] add_ln140_2_fu_362_p2;
wire   [8:0] select_ln137_2_fu_395_p3;
wire   [8:0] select_ln137_fu_388_p3;
wire   [8:0] idx_1_mid2_fu_409_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 j_fu_58 = 3'd0;
#0 idx_1_fu_62 = 9'd0;
#0 add_ln137_11_fu_66 = 9'd0;
#0 idx_fu_70 = 9'd0;
#0 add_ln1393_fu_74 = 9'd0;
#0 i_fu_78 = 3'd0;
#0 indvar_flatten133_fu_82 = 6'd0;
#0 c_fu_86 = 5'd0;
#0 indvars_iv172_fu_90 = 9'd0;
#0 indvar_flatten151_fu_94 = 9'd0;
#0 ap_done_reg = 1'b0;
end

conv2d_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_86 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            c_fu_86 <= select_ln137_4_fu_252_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_78 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_78 <= select_ln138_1_fu_278_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            idx_1_fu_62 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            idx_1_fu_62 <= add_ln140_fu_428_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            idx_fu_70 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            idx_fu_70 <= select_ln138_fu_416_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln137_fu_168_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten133_fu_82 <= select_ln138_2_fu_195_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten133_fu_82 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln137_fu_168_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten151_fu_94 <= add_ln137_2_fu_174_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten151_fu_94 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            indvars_iv172_fu_90 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            indvars_iv172_fu_90 <= select_ln137_3_fu_402_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_58 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_58 <= add_ln139_1_fu_322_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        add_ln137_11_fu_66 <= add_ln137_1_fu_440_p2;
        add_ln1393_fu_74 <= add_ln139_fu_434_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln140_1_reg_565 <= add_ln140_1_fu_312_p2;
        and_ln137_reg_554 <= and_ln137_fu_246_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln138_reg_543 <= icmp_ln138_fu_183_p2;
        icmp_ln138_reg_543_pp0_iter1_reg <= icmp_ln138_reg_543;
        j_4_mid2_reg_560 <= j_4_mid2_fu_270_p3;
        trunc_ln140_reg_570 <= trunc_ln140_fu_318_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln137_reg_554_pp0_iter2_reg <= and_ln137_reg_554;
        icmp_ln138_reg_543_pp0_iter2_reg <= icmp_ln138_reg_543_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((icmp_ln137_fu_168_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten133_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten133_load = indvar_flatten133_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten151_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten151_load = indvar_flatten151_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        fc_in_ce0_local = 1'b1;
    end else begin
        fc_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        fc_in_we0_local = 1'b1;
    end else begin
        fc_in_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pool2_out_ce0_local = 1'b1;
    end else begin
        pool2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln137_1_fu_440_p2 = (select_ln137_3_fu_402_p3 + 9'd25);

assign add_ln137_2_fu_174_p2 = (ap_sig_allocacmp_indvar_flatten151_load + 9'd1);

assign add_ln137_fu_222_p2 = (c_fu_86 + 5'd1);

assign add_ln138_1_fu_189_p2 = (ap_sig_allocacmp_indvar_flatten133_load + 6'd1);

assign add_ln138_fu_259_p2 = (select_ln137_1_fu_228_p3 + 3'd1);

assign add_ln139_1_fu_322_p2 = (j_4_mid2_fu_270_p3 + 3'd1);

assign add_ln139_2_fu_353_p2 = (p_shl_fu_346_p3 + zext_ln139_fu_343_p1);

assign add_ln139_fu_434_p2 = (select_ln138_fu_416_p3 + 9'd5);

assign add_ln140_1_fu_312_p2 = (add_ln140_3_fu_302_p2 + zext_ln140_2_fu_308_p1);

assign add_ln140_2_fu_362_p2 = (add_ln139_2_fu_353_p2 + zext_ln140_3_fu_359_p1);

assign add_ln140_3_fu_302_p2 = (zext_ln140_1_fu_298_p1 + zext_ln140_fu_286_p1);

assign add_ln140_fu_428_p2 = (idx_1_mid2_fu_409_p3 + 9'd1);

assign and_ln137_fu_246_p2 = (xor_ln137_fu_235_p2 & icmp_ln139_fu_240_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_265_p2 = (icmp_ln138_reg_543 | and_ln137_fu_246_p2);

assign fc_in_address0 = zext_ln139_1_fu_423_p1;

assign fc_in_ce0 = fc_in_ce0_local;

assign fc_in_d0 = pool2_out_q0;

assign fc_in_we0 = fc_in_we0_local;

assign icmp_ln137_fu_168_p2 = ((ap_sig_allocacmp_indvar_flatten151_load == 9'd400) ? 1'b1 : 1'b0);

assign icmp_ln138_fu_183_p2 = ((ap_sig_allocacmp_indvar_flatten133_load == 6'd25) ? 1'b1 : 1'b0);

assign icmp_ln139_fu_240_p2 = ((j_fu_58 == 3'd5) ? 1'b1 : 1'b0);

assign idx_1_mid2_fu_409_p3 = ((and_ln137_reg_554_pp0_iter2_reg[0:0] == 1'b1) ? add_ln1393_fu_74 : select_ln137_2_fu_395_p3);

assign j_4_mid2_fu_270_p3 = ((empty_fu_265_p2[0:0] == 1'b1) ? 3'd0 : j_fu_58);

assign p_shl_fu_346_p3 = {{trunc_ln140_reg_570}, {2'd0}};

assign pool2_out_address0 = zext_ln140_4_fu_368_p1;

assign pool2_out_ce0 = pool2_out_ce0_local;

assign select_ln137_1_fu_228_p3 = ((icmp_ln138_reg_543[0:0] == 1'b1) ? 3'd0 : i_fu_78);

assign select_ln137_2_fu_395_p3 = ((icmp_ln138_reg_543_pp0_iter2_reg[0:0] == 1'b1) ? add_ln137_11_fu_66 : idx_1_fu_62);

assign select_ln137_3_fu_402_p3 = ((icmp_ln138_reg_543_pp0_iter2_reg[0:0] == 1'b1) ? add_ln137_11_fu_66 : indvars_iv172_fu_90);

assign select_ln137_4_fu_252_p3 = ((icmp_ln138_reg_543[0:0] == 1'b1) ? add_ln137_fu_222_p2 : c_fu_86);

assign select_ln137_fu_388_p3 = ((icmp_ln138_reg_543_pp0_iter2_reg[0:0] == 1'b1) ? add_ln137_11_fu_66 : idx_fu_70);

assign select_ln138_1_fu_278_p3 = ((and_ln137_fu_246_p2[0:0] == 1'b1) ? add_ln138_fu_259_p2 : select_ln137_1_fu_228_p3);

assign select_ln138_2_fu_195_p3 = ((icmp_ln138_fu_183_p2[0:0] == 1'b1) ? 6'd1 : add_ln138_1_fu_189_p2);

assign select_ln138_fu_416_p3 = ((and_ln137_reg_554_pp0_iter2_reg[0:0] == 1'b1) ? add_ln1393_fu_74 : select_ln137_fu_388_p3);

assign tmp_fu_290_p3 = {{select_ln137_4_fu_252_p3}, {2'd0}};

assign trunc_ln140_fu_318_p1 = add_ln140_1_fu_312_p2[6:0];

assign xor_ln137_fu_235_p2 = (icmp_ln138_reg_543 ^ 1'd1);

assign zext_ln139_1_fu_423_p1 = idx_1_mid2_fu_409_p3;

assign zext_ln139_fu_343_p1 = add_ln140_1_reg_565;

assign zext_ln140_1_fu_298_p1 = tmp_fu_290_p3;

assign zext_ln140_2_fu_308_p1 = select_ln138_1_fu_278_p3;

assign zext_ln140_3_fu_359_p1 = j_4_mid2_reg_560;

assign zext_ln140_4_fu_368_p1 = add_ln140_2_fu_362_p2;

assign zext_ln140_fu_286_p1 = select_ln137_4_fu_252_p3;

endmodule //conv2d_conv2d_Pipeline_VITIS_LOOP_137_22_VITIS_LOOP_138_23_VITIS_LOOP_139_24
