-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_conv2d_Pipeline_VITIS_LOOP_86_12_VITIS_LOOP_87_13_VITIS_LOOP_91_14_VITIS_LOOP_92 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sum_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_WREADY : IN STD_LOGIC;
    m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RVALID : IN STD_LOGIC;
    m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_RLAST : IN STD_LOGIC;
    m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BVALID : IN STD_LOGIC;
    m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    phi_mul182 : IN STD_LOGIC_VECTOR (7 downto 0);
    pool1_out_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    pool1_out_ce0 : OUT STD_LOGIC;
    pool1_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln86 : IN STD_LOGIC_VECTOR (61 downto 0);
    conv2_out_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_out_ce0 : OUT STD_LOGIC;
    conv2_out_we0 : OUT STD_LOGIC;
    conv2_out_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    conv2_out_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_out_1_ce0 : OUT STD_LOGIC;
    conv2_out_1_we0 : OUT STD_LOGIC;
    conv2_out_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1035_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1035_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1035_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1035_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1035_p_ce : OUT STD_LOGIC;
    grp_fu_1039_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1039_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1039_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1039_p_ce : OUT STD_LOGIC;
    grp_fu_1043_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1043_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1043_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1043_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1043_p_ce : OUT STD_LOGIC );
end;


architecture behav of conv2d_conv2d_Pipeline_VITIS_LOOP_86_12_VITIS_LOOP_87_13_VITIS_LOOP_91_14_VITIS_LOOP_92 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv14_2208 : STD_LOGIC_VECTOR (13 downto 0) := "10001000001000";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv11_318 : STD_LOGIC_VECTOR (10 downto 0) := "01100011000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv8_48 : STD_LOGIC_VECTOR (7 downto 0) := "01001000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv8_D : STD_LOGIC_VECTOR (7 downto 0) := "00001101";
    constant ap_const_lv11_D : STD_LOGIC_VECTOR (10 downto 0) := "00000001101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln86_reg_991 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage5 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem1_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_grp1 : BOOLEAN;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal sext_ln86_cast_fu_252_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln86_cast_reg_986 : STD_LOGIC_VECTOR (62 downto 0);
    signal icmp_ln86_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln86_reg_991_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln86_reg_991_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_reg_995 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_reg_995_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_reg_995_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln86_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln86_reg_1004 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_reg_1010 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln86_2_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln86_2_reg_1015 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln86_2_reg_1015_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln86_2_reg_1015_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten46_mid2105_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten46_mid2105_reg_1023 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln92_1_fu_372_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln92_1_reg_1029 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln91_1_fu_378_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln91_1_reg_1034 : STD_LOGIC_VECTOR (7 downto 0);
    signal kj_mid2_fu_516_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal kj_mid2_reg_1039 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal add_ln92_2_fu_552_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln92_2_reg_1050 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln92_2_fu_558_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln92_2_reg_1055 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln98_fu_570_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln98_reg_1060 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln93_1_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_1_reg_1065 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_1_reg_1065_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_1_reg_1065_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_1_reg_1065_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_1_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_1_reg_1069 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_1_reg_1069_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_1_reg_1069_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_1_reg_1069_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_1_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_1_reg_1073 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_1_reg_1073_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_1_reg_1073_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln91_1_reg_1073_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem1_addr_reg_1077 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal select_ln86_2_fu_688_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln86_2_reg_1083 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage4_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage4_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage4_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal select_ln86_2_reg_1083_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln86_2_reg_1083_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln86_2_reg_1083_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal select_ln86_fu_715_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln86_reg_1098 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln87_fu_733_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln87_reg_1104 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln87_reg_1104_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln87_reg_1104_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln1_reg_1113 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln1_reg_1113_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln1_reg_1113_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal pool1_out_load_reg_1123 : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem1_addr_read_reg_1128 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp2 : BOOLEAN;
    signal bitcast_ln101_fu_769_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_19_mid257_fu_782_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_19_mid257_reg_1138 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul2_reg_1143 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_reg_1148 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln107_fu_795_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln107_reg_1156 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_2_fu_841_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_2_reg_1162 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln100_4_fu_765_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln107_3_fu_881_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal sext_ln101_fu_669_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_block_state5_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage4_11001_grp1 : BOOLEAN;
    signal sum_fu_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_sum_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage4_grp0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal kj_fu_134 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln93_fu_576_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ki_fu_138 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln92_fu_524_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten29_fu_142 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln92_1_fu_600_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ic_fu_146 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln91_fu_490_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten44_fu_150 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln91_1_fu_607_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal j_fu_154 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln87_fu_727_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten70_fu_158 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal select_ln87_1_fu_390_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_fu_162 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten106_fu_166 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal add_ln86_1_fu_324_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal pool1_out_ce0_local : STD_LOGIC;
    signal conv2_out_we0_local : STD_LOGIC;
    signal conv2_out_ce0_local : STD_LOGIC;
    signal conv2_out_1_we0_local : STD_LOGIC;
    signal conv2_out_1_ce0_local : STD_LOGIC;
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal icmp_ln91_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten46_not_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln87_1_fu_384_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln93_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln86_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln86_1_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ic_mid251_fu_432_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond_flatten31_mid269_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_29_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_30_fu_465_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_mid265_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten31_mid269_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln91_fu_454_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ki_mid236_fu_470_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_31_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_mid243_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_32_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln92_fu_498_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln92_fu_540_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_shl2_fu_544_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln92_fu_536_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_fu_562_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln92_1_fu_639_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln100_fu_642_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln101_1_fu_648_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln93_1_fu_645_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln101_2_fu_658_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln101_fu_654_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln101_fu_663_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln86_fu_682_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln100_fu_695_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_887_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln87_fu_722_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln93_2_fu_737_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln100_1_fu_740_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_896_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln86_1_fu_776_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln107_fu_792_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal bitcast_ln106_fu_800_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_803_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln106_fu_813_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln106_1_fu_823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln106_fu_817_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln106_fu_829_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln106_fu_835_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_855_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl1_fu_848_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln107_1_fu_862_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln107_fu_866_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln107_2_fu_872_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln107_1_fu_875_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_887_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_887_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_887_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_896_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_896_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_896_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_239_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal grp_fu_243_ce : STD_LOGIC;
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal grp_fu_247_ce : STD_LOGIC;
    signal ap_block_pp0_stage4_00001_grp0 : BOOLEAN;
    signal grp_fu_887_ce : STD_LOGIC;
    signal grp_fu_896_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_block_pp0_stage5_00001 : BOOLEAN;
    signal grp_fu_887_p00 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_887_p20 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_896_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_896_p20 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_mac_muladd_4ns_4ns_4ns_8_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component conv2d_mac_muladd_8ns_4ns_4ns_11_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component conv2d_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_4ns_4ns_4ns_8_4_1_U40 : component conv2d_mac_muladd_4ns_4ns_4ns_8_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_887_p0,
        din1 => grp_fu_887_p1,
        din2 => grp_fu_887_p2,
        ce => grp_fu_887_ce,
        dout => grp_fu_887_p3);

    mac_muladd_8ns_4ns_4ns_11_4_1_U41 : component conv2d_mac_muladd_8ns_4ns_4ns_11_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        dout_WIDTH => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_896_p0,
        din1 => grp_fu_896_p1,
        din2 => grp_fu_896_p2,
        ce => grp_fu_896_ce,
        dout => grp_fu_896_p3);

    flow_control_loop_pipe_sequential_init_U : component conv2d_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage5,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage4_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage4_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then 
                        ap_block_pp0_stage4_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0)) then 
                        ap_block_pp0_stage4_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage5)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    i_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_fu_162 <= ap_const_lv4_0;
            elsif (((icmp_ln86_reg_991 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                i_fu_162 <= select_ln86_2_fu_688_p3;
            end if; 
        end if;
    end process;

    ic_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ic_fu_146 <= ap_const_lv4_0;
            elsif (((icmp_ln86_reg_991 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ic_fu_146 <= select_ln91_fu_490_p3;
            end if; 
        end if;
    end process;

    indvar_flatten106_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten106_fu_166 <= ap_const_lv14_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln86_fu_318_p2 = ap_const_lv1_0))) then 
                indvar_flatten106_fu_166 <= add_ln86_1_fu_324_p2;
            end if; 
        end if;
    end process;

    indvar_flatten29_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten29_fu_142 <= ap_const_lv4_0;
            elsif (((icmp_ln86_reg_991 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                indvar_flatten29_fu_142 <= select_ln92_1_fu_600_p3;
            end if; 
        end if;
    end process;

    indvar_flatten44_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten44_fu_150 <= ap_const_lv8_0;
            elsif (((icmp_ln86_reg_991 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                indvar_flatten44_fu_150 <= select_ln91_1_fu_607_p3;
            end if; 
        end if;
    end process;

    indvar_flatten70_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten70_fu_158 <= ap_const_lv11_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln86_fu_318_p2 = ap_const_lv1_0))) then 
                indvar_flatten70_fu_158 <= select_ln87_1_fu_390_p3;
            end if; 
        end if;
    end process;

    j_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_fu_154 <= ap_const_lv4_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                j_fu_154 <= select_ln87_fu_727_p3;
            end if; 
        end if;
    end process;

    ki_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ki_fu_138 <= ap_const_lv2_0;
            elsif (((icmp_ln86_reg_991 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                ki_fu_138 <= select_ln92_fu_524_p3;
            end if; 
        end if;
    end process;

    kj_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                kj_fu_134 <= ap_const_lv2_0;
            elsif (((icmp_ln86_reg_991 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                kj_fu_134 <= add_ln93_fu_576_p2;
            end if; 
        end if;
    end process;

    sum_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                sum_fu_130 <= sum_11;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                sum_fu_130 <= sum_1_reg_1148;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                add_ln107_reg_1156 <= add_ln107_fu_795_p2;
                sum_2_reg_1162 <= sum_2_fu_841_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln91_1_reg_1034 <= add_ln91_1_fu_378_p2;
                add_ln92_1_reg_1029 <= add_ln92_1_fu_372_p2;
                and_ln86_2_reg_1015 <= and_ln86_2_fu_354_p2;
                and_ln86_2_reg_1015_pp0_iter1_reg <= and_ln86_2_reg_1015;
                and_ln86_2_reg_1015_pp0_iter2_reg <= and_ln86_2_reg_1015_pp0_iter1_reg;
                icmp_ln86_reg_991 <= icmp_ln86_fu_318_p2;
                icmp_ln86_reg_991_pp0_iter1_reg <= icmp_ln86_reg_991;
                icmp_ln86_reg_991_pp0_iter2_reg <= icmp_ln86_reg_991_pp0_iter1_reg;
                icmp_ln87_reg_995 <= icmp_ln87_fu_330_p2;
                icmp_ln87_reg_995_pp0_iter1_reg <= icmp_ln87_reg_995;
                icmp_ln87_reg_995_pp0_iter2_reg <= icmp_ln87_reg_995_pp0_iter1_reg;
                icmp_ln92_reg_1010 <= icmp_ln92_fu_342_p2;
                lshr_ln1_reg_1113 <= select_ln87_fu_727_p3(3 downto 1);
                lshr_ln1_reg_1113_pp0_iter2_reg <= lshr_ln1_reg_1113;
                lshr_ln1_reg_1113_pp0_iter3_reg <= lshr_ln1_reg_1113_pp0_iter2_reg;
                not_exitcond_flatten46_mid2105_reg_1023 <= not_exitcond_flatten46_mid2105_fu_366_p2;
                trunc_ln87_reg_1104 <= trunc_ln87_fu_733_p1;
                trunc_ln87_reg_1104_pp0_iter2_reg <= trunc_ln87_reg_1104;
                trunc_ln87_reg_1104_pp0_iter3_reg <= trunc_ln87_reg_1104_pp0_iter2_reg;
                xor_ln86_reg_1004 <= xor_ln86_fu_336_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                add_ln92_2_reg_1050 <= add_ln92_2_fu_552_p2;
                icmp_ln91_1_reg_1073 <= icmp_ln91_1_fu_594_p2;
                icmp_ln91_1_reg_1073_pp0_iter1_reg <= icmp_ln91_1_reg_1073;
                icmp_ln91_1_reg_1073_pp0_iter2_reg <= icmp_ln91_1_reg_1073_pp0_iter1_reg;
                icmp_ln91_1_reg_1073_pp0_iter3_reg <= icmp_ln91_1_reg_1073_pp0_iter2_reg;
                icmp_ln92_1_reg_1069 <= icmp_ln92_1_fu_588_p2;
                icmp_ln92_1_reg_1069_pp0_iter1_reg <= icmp_ln92_1_reg_1069;
                icmp_ln92_1_reg_1069_pp0_iter2_reg <= icmp_ln92_1_reg_1069_pp0_iter1_reg;
                icmp_ln92_1_reg_1069_pp0_iter3_reg <= icmp_ln92_1_reg_1069_pp0_iter2_reg;
                icmp_ln93_1_reg_1065 <= icmp_ln93_1_fu_582_p2;
                icmp_ln93_1_reg_1065_pp0_iter1_reg <= icmp_ln93_1_reg_1065;
                icmp_ln93_1_reg_1065_pp0_iter2_reg <= icmp_ln93_1_reg_1065_pp0_iter1_reg;
                icmp_ln93_1_reg_1065_pp0_iter3_reg <= icmp_ln93_1_reg_1065_pp0_iter2_reg;
                kj_mid2_reg_1039 <= kj_mid2_fu_516_p3;
                sub_ln98_reg_1060 <= sub_ln98_fu_570_p2;
                    zext_ln92_2_reg_1055(1 downto 0) <= zext_ln92_2_fu_558_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                gmem1_addr_read_reg_1128 <= m_axi_gmem1_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                gmem1_addr_reg_1077 <= sext_ln101_fu_669_p1;
                pool1_out_load_reg_1123 <= pool1_out_q0;
                sum_1_reg_1148 <= grp_fu_1035_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                mul2_reg_1143 <= grp_fu_1039_p_dout0;
                select_ln86_2_reg_1083 <= select_ln86_2_fu_688_p3;
                select_ln86_2_reg_1083_pp0_iter1_reg <= select_ln86_2_reg_1083;
                select_ln86_2_reg_1083_pp0_iter2_reg <= select_ln86_2_reg_1083_pp0_iter1_reg;
                select_ln86_2_reg_1083_pp0_iter3_reg <= select_ln86_2_reg_1083_pp0_iter2_reg;
                sum_19_mid257_reg_1138 <= sum_19_mid257_fu_782_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln86_reg_1098 <= select_ln86_fu_715_p3;
                sext_ln86_cast_reg_986 <= sext_ln86_cast_fu_252_p1;
            end if;
        end if;
    end process;
    zext_ln92_2_reg_1055(3 downto 2) <= "00";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage5_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage4_subdone, ap_condition_exit_pp0_iter3_stage0, ap_idle_pp0_0to2, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln100_1_fu_740_p2 <= std_logic_vector(unsigned(zext_ln93_2_fu_737_p1) + unsigned(select_ln87_fu_727_p3));
    add_ln100_fu_695_p2 <= std_logic_vector(unsigned(zext_ln92_2_reg_1055) + unsigned(select_ln86_2_fu_688_p3));
    add_ln101_1_fu_648_p2 <= std_logic_vector(unsigned(zext_ln92_1_fu_639_p1) + unsigned(zext_ln100_fu_642_p1));
    add_ln101_2_fu_658_p2 <= std_logic_vector(unsigned(zext_ln93_1_fu_645_p1) + unsigned(sext_ln86_cast_reg_986));
    add_ln101_fu_663_p2 <= std_logic_vector(unsigned(add_ln101_2_fu_658_p2) + unsigned(zext_ln101_fu_654_p1));
    add_ln107_1_fu_875_p2 <= std_logic_vector(unsigned(sub_ln107_fu_866_p2) + unsigned(zext_ln107_2_fu_872_p1));
    add_ln107_fu_795_p2 <= std_logic_vector(unsigned(phi_mul182) + unsigned(zext_ln107_fu_792_p1));
    add_ln86_1_fu_324_p2 <= std_logic_vector(unsigned(indvar_flatten106_fu_166) + unsigned(ap_const_lv14_1));
    add_ln86_fu_682_p2 <= std_logic_vector(unsigned(i_fu_162) + unsigned(ap_const_lv4_1));
    add_ln87_1_fu_384_p2 <= std_logic_vector(unsigned(indvar_flatten70_fu_158) + unsigned(ap_const_lv11_1));
    add_ln87_fu_722_p2 <= std_logic_vector(unsigned(select_ln86_reg_1098) + unsigned(ap_const_lv4_1));
    add_ln91_1_fu_378_p2 <= std_logic_vector(unsigned(indvar_flatten44_fu_150) + unsigned(ap_const_lv8_1));
    add_ln91_fu_454_p2 <= std_logic_vector(unsigned(ic_mid251_fu_432_p3) + unsigned(ap_const_lv4_1));
    add_ln92_1_fu_372_p2 <= std_logic_vector(unsigned(indvar_flatten29_fu_142) + unsigned(ap_const_lv4_1));
    add_ln92_2_fu_552_p2 <= std_logic_vector(unsigned(p_shl2_fu_544_p3) + unsigned(zext_ln92_fu_536_p1));
    add_ln92_fu_498_p2 <= std_logic_vector(unsigned(ki_mid236_fu_470_p3) + unsigned(ap_const_lv2_1));
    add_ln93_fu_576_p2 <= std_logic_vector(unsigned(kj_mid2_fu_516_p3) + unsigned(ap_const_lv2_1));
    and_ln106_fu_835_p2 <= (or_ln106_fu_829_p2 and grp_fu_1043_p_dout0);
    and_ln86_1_fu_445_p2 <= (xor_ln86_reg_1004 and icmp_ln92_reg_1010);
    and_ln86_2_fu_354_p2 <= (xor_ln86_fu_336_p2 and icmp_ln91_fu_348_p2);
    and_ln86_fu_423_p2 <= (xor_ln86_reg_1004 and icmp_ln93_fu_417_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem1_0_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (m_axi_gmem1_0_RVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem1_0_RVALID)
    begin
                ap_block_pp0_stage0_11001_grp2 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (m_axi_gmem1_0_RVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem1_0_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (m_axi_gmem1_0_RVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_00001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_11001_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_io_grp1)
    begin
                ap_block_pp0_stage4_11001 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1));
    end process;

        ap_block_pp0_stage4_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_io_grp1)
    begin
                ap_block_pp0_stage4_11001_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1));
    end process;

        ap_block_pp0_stage4_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_block_state5_io_grp1)
    begin
                ap_block_pp0_stage4_subdone <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_io_grp1));
    end process;

        ap_block_pp0_stage4_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_io_grp1_assign_proc : process(icmp_ln86_reg_991, m_axi_gmem1_0_ARREADY)
    begin
                ap_block_state5_io_grp1 <= ((m_axi_gmem1_0_ARREADY = ap_const_logic_0) and (icmp_ln86_reg_991 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage5_assign_proc : process(ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln86_reg_991)
    begin
        if (((icmp_ln86_reg_991 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            ap_condition_exit_pp0_iter0_stage5 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone, icmp_ln86_reg_991_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln86_reg_991_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage5;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_sum_load_assign_proc : process(ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage4, sum_1_reg_1148, sum_fu_130, ap_block_pp0_stage4_grp0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage4_grp0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            ap_sig_allocacmp_sum_load <= sum_1_reg_1148;
        else 
            ap_sig_allocacmp_sum_load <= sum_fu_130;
        end if; 
    end process;

    bitcast_ln101_fu_769_p1 <= gmem1_addr_read_reg_1128;
    bitcast_ln106_fu_800_p1 <= sum_1_reg_1148;
    conv2_out_1_address0 <= zext_ln107_3_fu_881_p1(11 - 1 downto 0);
    conv2_out_1_ce0 <= conv2_out_1_ce0_local;

    conv2_out_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_1_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_1_d0 <= sum_2_reg_1162;
    conv2_out_1_we0 <= conv2_out_1_we0_local;

    conv2_out_1_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln93_1_reg_1065_pp0_iter3_reg, icmp_ln92_1_reg_1069_pp0_iter3_reg, icmp_ln91_1_reg_1073_pp0_iter3_reg, trunc_ln87_reg_1104_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (trunc_ln87_reg_1104_pp0_iter3_reg = ap_const_lv1_1) and (icmp_ln91_1_reg_1073_pp0_iter3_reg = ap_const_lv1_1) and (icmp_ln92_1_reg_1069_pp0_iter3_reg = ap_const_lv1_1) and (icmp_ln93_1_reg_1065_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_1_we0_local <= ap_const_logic_1;
        else 
            conv2_out_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_address0 <= zext_ln107_3_fu_881_p1(11 - 1 downto 0);
    conv2_out_ce0 <= conv2_out_ce0_local;

    conv2_out_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_d0 <= sum_2_reg_1162;
    conv2_out_we0 <= conv2_out_we0_local;

    conv2_out_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, icmp_ln93_1_reg_1065_pp0_iter3_reg, icmp_ln92_1_reg_1069_pp0_iter3_reg, icmp_ln91_1_reg_1073_pp0_iter3_reg, trunc_ln87_reg_1104_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (trunc_ln87_reg_1104_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln91_1_reg_1073_pp0_iter3_reg = ap_const_lv1_1) and (icmp_ln92_1_reg_1069_pp0_iter3_reg = ap_const_lv1_1) and (icmp_ln93_1_reg_1065_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            conv2_out_we0_local <= ap_const_logic_1;
        else 
            conv2_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_29_fu_460_p2 <= (exitcond_flatten31_mid269_fu_449_p2 or and_ln86_2_reg_1015);
    empty_30_fu_465_p2 <= (icmp_ln87_reg_995 or empty_29_fu_460_p2);
    empty_31_fu_504_p2 <= (exitcond_flatten31_mid269_fu_449_p2 or empty_fu_428_p2);
    empty_32_fu_510_p2 <= (icmp_ln93_mid243_fu_484_p2 or empty_31_fu_504_p2);
    empty_fu_428_p2 <= (icmp_ln87_reg_995 or and_ln86_2_reg_1015);
    exitcond_flatten31_mid269_fu_449_p2 <= (not_exitcond_flatten46_mid2105_reg_1023 and and_ln86_1_fu_445_p2);
    exitcond_flatten46_not_fu_360_p2 <= (icmp_ln91_fu_348_p2 xor ap_const_lv1_1);

    gmem1_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln86_reg_991, m_axi_gmem1_0_ARREADY, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_grp1)
    begin
        if (((icmp_ln86_reg_991 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            gmem1_blk_n_AR <= m_axi_gmem1_0_ARREADY;
        else 
            gmem1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, m_axi_gmem1_0_RVALID, ap_block_pp0_stage0_grp2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem1_blk_n_R <= m_axi_gmem1_0_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_1035_p_ce <= grp_fu_239_ce;
    grp_fu_1035_p_din0 <= sum_19_mid257_reg_1138;
    grp_fu_1035_p_din1 <= mul2_reg_1143;
    grp_fu_1035_p_opcode <= ap_const_lv2_0;
    grp_fu_1039_p_ce <= grp_fu_243_ce;
    grp_fu_1039_p_din0 <= pool1_out_load_reg_1123;
    grp_fu_1039_p_din1 <= bitcast_ln101_fu_769_p1;
    grp_fu_1043_p_ce <= grp_fu_247_ce;
    grp_fu_1043_p_din0 <= sum_1_reg_1148;
    grp_fu_1043_p_din1 <= ap_const_lv32_0;
    grp_fu_1043_p_opcode <= ap_const_lv5_4;

    grp_fu_239_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage5_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_239_ce <= ap_const_logic_1;
        else 
            grp_fu_239_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_243_ce_assign_proc : process(ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001_grp0, ap_block_pp0_stage4_subdone_grp0_done_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            grp_fu_243_ce <= ap_const_logic_1;
        else 
            grp_fu_243_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_247_ce_assign_proc : process(ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001_grp0, ap_block_pp0_stage4_subdone_grp0_done_reg, ap_block_pp0_stage5_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)))) then 
            grp_fu_247_ce <= ap_const_logic_1;
        else 
            grp_fu_247_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_887_ce_assign_proc : process(ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_block_pp0_stage4_11001_grp0, ap_block_pp0_stage4_subdone_grp0_done_reg, ap_block_pp0_stage5_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            grp_fu_887_ce <= ap_const_logic_1;
        else 
            grp_fu_887_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_887_p0 <= grp_fu_887_p00(4 - 1 downto 0);
    grp_fu_887_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln91_fu_490_p3),8));
    grp_fu_887_p1 <= ap_const_lv8_D(4 - 1 downto 0);
    grp_fu_887_p2 <= grp_fu_887_p20(4 - 1 downto 0);
    grp_fu_887_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln100_fu_695_p2),8));

    grp_fu_896_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage5_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_896_ce <= ap_const_logic_1;
        else 
            grp_fu_896_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_896_p0 <= grp_fu_896_p00(8 - 1 downto 0);
    grp_fu_896_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_887_p3),11));
    grp_fu_896_p1 <= ap_const_lv11_D(4 - 1 downto 0);
    grp_fu_896_p2 <= grp_fu_896_p20(4 - 1 downto 0);
    grp_fu_896_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln100_1_fu_740_p2),11));
    ic_mid251_fu_432_p3 <= 
        ap_const_lv4_0 when (empty_fu_428_p2(0) = '1') else 
        ic_fu_146;
    icmp_ln106_1_fu_823_p2 <= "1" when (trunc_ln106_fu_813_p1 = ap_const_lv23_0) else "0";
    icmp_ln106_fu_817_p2 <= "0" when (tmp_s_fu_803_p4 = ap_const_lv8_FF) else "1";
    icmp_ln86_fu_318_p2 <= "1" when (indvar_flatten106_fu_166 = ap_const_lv14_2208) else "0";
    icmp_ln87_fu_330_p2 <= "1" when (indvar_flatten70_fu_158 = ap_const_lv11_318) else "0";
    icmp_ln91_1_fu_594_p2 <= "1" when (select_ln91_fu_490_p3 = ap_const_lv4_7) else "0";
    icmp_ln91_fu_348_p2 <= "1" when (indvar_flatten44_fu_150 = ap_const_lv8_48) else "0";
    icmp_ln92_1_fu_588_p2 <= "1" when (select_ln92_fu_524_p3 = ap_const_lv2_2) else "0";
    icmp_ln92_fu_342_p2 <= "1" when (indvar_flatten29_fu_142 = ap_const_lv4_9) else "0";
    icmp_ln93_1_fu_582_p2 <= "1" when (add_ln93_fu_576_p2 = ap_const_lv2_3) else "0";
    icmp_ln93_fu_417_p2 <= "1" when (kj_fu_134 = ap_const_lv2_3) else "0";
    icmp_ln93_mid243_fu_484_p2 <= (not_exitcond_flatten31_mid269_fu_478_p2 and icmp_ln93_mid265_fu_440_p2);
    icmp_ln93_mid265_fu_440_p2 <= (not_exitcond_flatten46_mid2105_reg_1023 and and_ln86_fu_423_p2);
    ki_mid236_fu_470_p3 <= 
        ap_const_lv2_0 when (empty_30_fu_465_p2(0) = '1') else 
        ki_fu_138;
    kj_mid2_fu_516_p3 <= 
        ap_const_lv2_0 when (empty_32_fu_510_p2(0) = '1') else 
        kj_fu_134;
    m_axi_gmem1_0_ARADDR <= gmem1_addr_reg_1077;
    m_axi_gmem1_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_ARID <= ap_const_lv1_0;
    m_axi_gmem1_0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_gmem1_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem1_0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter0_reg, icmp_ln86_reg_991, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001_grp1)
    begin
        if (((icmp_ln86_reg_991 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            m_axi_gmem1_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem1_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_AWID <= ap_const_lv1_0;
    m_axi_gmem1_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_0_BREADY <= ap_const_logic_0;

    m_axi_gmem1_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem1_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_0_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_0_WID <= ap_const_lv1_0;
    m_axi_gmem1_0_WLAST <= ap_const_logic_0;
    m_axi_gmem1_0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_WVALID <= ap_const_logic_0;
    not_exitcond_flatten31_mid269_fu_478_p2 <= (exitcond_flatten31_mid269_fu_449_p2 xor ap_const_lv1_1);
    not_exitcond_flatten46_mid2105_fu_366_p2 <= (icmp_ln87_fu_330_p2 or exitcond_flatten46_not_fu_360_p2);
    or_ln106_fu_829_p2 <= (icmp_ln106_fu_817_p2 or icmp_ln106_1_fu_823_p2);
    p_shl1_fu_848_p3 <= (add_ln107_reg_1156 & ap_const_lv3_0);
    p_shl2_fu_544_p3 <= (trunc_ln92_fu_540_p1 & ap_const_lv3_0);
    p_shl_fu_562_p3 <= (select_ln92_fu_524_p3 & ap_const_lv2_0);
    pool1_out_address0 <= zext_ln100_4_fu_765_p1(11 - 1 downto 0);
    pool1_out_ce0 <= pool1_out_ce0_local;

    pool1_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            pool1_out_ce0_local <= ap_const_logic_1;
        else 
            pool1_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln86_1_fu_776_p3 <= 
        sum_11 when (icmp_ln87_reg_995_pp0_iter2_reg(0) = '1') else 
        ap_sig_allocacmp_sum_load;
    select_ln86_2_fu_688_p3 <= 
        add_ln86_fu_682_p2 when (icmp_ln87_reg_995(0) = '1') else 
        i_fu_162;
    select_ln86_fu_715_p3 <= 
        ap_const_lv4_0 when (icmp_ln87_reg_995(0) = '1') else 
        j_fu_154;
    select_ln87_1_fu_390_p3 <= 
        ap_const_lv11_1 when (icmp_ln87_fu_330_p2(0) = '1') else 
        add_ln87_1_fu_384_p2;
    select_ln87_fu_727_p3 <= 
        add_ln87_fu_722_p2 when (and_ln86_2_reg_1015(0) = '1') else 
        select_ln86_reg_1098;
    select_ln91_1_fu_607_p3 <= 
        ap_const_lv8_1 when (empty_fu_428_p2(0) = '1') else 
        add_ln91_1_reg_1034;
    select_ln91_fu_490_p3 <= 
        add_ln91_fu_454_p2 when (exitcond_flatten31_mid269_fu_449_p2(0) = '1') else 
        ic_mid251_fu_432_p3;
    select_ln92_1_fu_600_p3 <= 
        ap_const_lv4_1 when (empty_30_fu_465_p2(0) = '1') else 
        add_ln92_1_reg_1029;
    select_ln92_fu_524_p3 <= 
        add_ln92_fu_498_p2 when (icmp_ln93_mid243_fu_484_p2(0) = '1') else 
        ki_mid236_fu_470_p3;
        sext_ln101_fu_669_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln101_fu_663_p2),64));

        sext_ln86_cast_fu_252_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln86),63));

    sub_ln107_fu_866_p2 <= std_logic_vector(unsigned(p_shl1_fu_848_p3) - unsigned(zext_ln107_1_fu_862_p1));
    sub_ln98_fu_570_p2 <= std_logic_vector(unsigned(p_shl_fu_562_p3) - unsigned(zext_ln92_2_fu_558_p1));
    sum_19_mid257_fu_782_p3 <= 
        sum_11 when (and_ln86_2_reg_1015_pp0_iter2_reg(0) = '1') else 
        select_ln86_1_fu_776_p3;
    sum_2_fu_841_p3 <= 
        ap_const_lv32_0 when (and_ln106_fu_835_p2(0) = '1') else 
        sum_1_reg_1148;
    tmp_fu_855_p3 <= (add_ln107_reg_1156 & ap_const_lv1_0);
    tmp_s_fu_803_p4 <= bitcast_ln106_fu_800_p1(30 downto 23);
    trunc_ln106_fu_813_p1 <= bitcast_ln106_fu_800_p1(23 - 1 downto 0);
    trunc_ln87_fu_733_p1 <= select_ln87_fu_727_p3(1 - 1 downto 0);
    trunc_ln92_fu_540_p1 <= select_ln91_fu_490_p3(3 - 1 downto 0);
    xor_ln86_fu_336_p2 <= (icmp_ln87_fu_330_p2 xor ap_const_lv1_1);
    zext_ln100_4_fu_765_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_896_p3),64));
    zext_ln100_fu_642_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln98_reg_1060),7));
    zext_ln101_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln101_1_fu_648_p2),63));
    zext_ln107_1_fu_862_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_855_p3),11));
    zext_ln107_2_fu_872_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_reg_1113_pp0_iter3_reg),11));
    zext_ln107_3_fu_881_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln107_1_fu_875_p2),64));
    zext_ln107_fu_792_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln86_2_reg_1083_pp0_iter3_reg),8));
    zext_ln92_1_fu_639_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln92_2_reg_1050),7));
    zext_ln92_2_fu_558_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln92_fu_524_p3),4));
    zext_ln92_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln91_fu_490_p3),6));
    zext_ln93_1_fu_645_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kj_mid2_reg_1039),63));
    zext_ln93_2_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kj_mid2_reg_1039),4));
end behav;
