-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_conv2d_Pipeline_VITIS_LOOP_137_22_VITIS_LOOP_138_23_VITIS_LOOP_139_24 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pool2_out_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    pool2_out_ce0 : OUT STD_LOGIC;
    pool2_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    fc_in_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    fc_in_ce0 : OUT STD_LOGIC;
    fc_in_we0 : OUT STD_LOGIC;
    fc_in_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of conv2d_conv2d_Pipeline_VITIS_LOOP_137_22_VITIS_LOOP_138_23_VITIS_LOOP_139_24 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv9_190 : STD_LOGIC_VECTOR (8 downto 0) := "110010000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv9_5 : STD_LOGIC_VECTOR (8 downto 0) := "000000101";
    constant ap_const_lv9_19 : STD_LOGIC_VECTOR (8 downto 0) := "000011001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln137_fu_168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln138_fu_183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_reg_543 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_reg_543_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_reg_543_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln137_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln137_reg_554 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln137_reg_554_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal j_4_mid2_fu_270_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_4_mid2_reg_560 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln140_1_fu_312_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln140_1_reg_565 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln140_fu_318_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln140_reg_570 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln140_4_fu_368_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln139_1_fu_423_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_58 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln139_1_fu_322_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal idx_1_fu_62 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln140_fu_428_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln137_11_fu_66 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln137_1_fu_440_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal idx_fu_70 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln138_fu_416_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln1393_fu_74 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln139_fu_434_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_fu_78 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln138_1_fu_278_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten133_fu_82 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln138_2_fu_195_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten133_load : STD_LOGIC_VECTOR (5 downto 0);
    signal c_fu_86 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal select_ln137_4_fu_252_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvars_iv172_fu_90 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln137_3_fu_402_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal indvar_flatten151_fu_94 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln137_2_fu_174_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_indvar_flatten151_load : STD_LOGIC_VECTOR (8 downto 0);
    signal pool2_out_ce0_local : STD_LOGIC;
    signal fc_in_we0_local : STD_LOGIC;
    signal fc_in_ce0_local : STD_LOGIC;
    signal add_ln138_1_fu_189_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln139_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln137_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln137_fu_222_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln137_1_fu_228_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln138_fu_259_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_290_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln140_1_fu_298_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln140_fu_286_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln140_3_fu_302_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln140_2_fu_308_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl_fu_346_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln139_fu_343_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln139_2_fu_353_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln140_3_fu_359_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln140_2_fu_362_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln137_2_fu_395_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln137_fu_388_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal idx_1_mid2_fu_409_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component conv2d_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    c_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_86 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    c_fu_86 <= select_ln137_4_fu_252_p3;
                end if;
            end if; 
        end if;
    end process;

    i_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_78 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_78 <= select_ln138_1_fu_278_p3;
                end if;
            end if; 
        end if;
    end process;

    idx_1_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    idx_1_fu_62 <= ap_const_lv9_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    idx_1_fu_62 <= add_ln140_fu_428_p2;
                end if;
            end if; 
        end if;
    end process;

    idx_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    idx_fu_70 <= ap_const_lv9_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    idx_fu_70 <= select_ln138_fu_416_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten133_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln137_fu_168_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten133_fu_82 <= select_ln138_2_fu_195_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten133_fu_82 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten151_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln137_fu_168_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten151_fu_94 <= add_ln137_2_fu_174_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten151_fu_94 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    indvars_iv172_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    indvars_iv172_fu_90 <= ap_const_lv9_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    indvars_iv172_fu_90 <= select_ln137_3_fu_402_p3;
                end if;
            end if; 
        end if;
    end process;

    j_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_58 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_58 <= add_ln139_1_fu_322_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                add_ln137_11_fu_66 <= add_ln137_1_fu_440_p2;
                add_ln1393_fu_74 <= add_ln139_fu_434_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln140_1_reg_565 <= add_ln140_1_fu_312_p2;
                and_ln137_reg_554 <= and_ln137_fu_246_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln138_reg_543 <= icmp_ln138_fu_183_p2;
                icmp_ln138_reg_543_pp0_iter1_reg <= icmp_ln138_reg_543;
                j_4_mid2_reg_560 <= j_4_mid2_fu_270_p3;
                trunc_ln140_reg_570 <= trunc_ln140_fu_318_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                and_ln137_reg_554_pp0_iter2_reg <= and_ln137_reg_554;
                icmp_ln138_reg_543_pp0_iter2_reg <= icmp_ln138_reg_543_pp0_iter1_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln137_1_fu_440_p2 <= std_logic_vector(unsigned(select_ln137_3_fu_402_p3) + unsigned(ap_const_lv9_19));
    add_ln137_2_fu_174_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten151_load) + unsigned(ap_const_lv9_1));
    add_ln137_fu_222_p2 <= std_logic_vector(unsigned(c_fu_86) + unsigned(ap_const_lv5_1));
    add_ln138_1_fu_189_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten133_load) + unsigned(ap_const_lv6_1));
    add_ln138_fu_259_p2 <= std_logic_vector(unsigned(select_ln137_1_fu_228_p3) + unsigned(ap_const_lv3_1));
    add_ln139_1_fu_322_p2 <= std_logic_vector(unsigned(j_4_mid2_fu_270_p3) + unsigned(ap_const_lv3_1));
    add_ln139_2_fu_353_p2 <= std_logic_vector(unsigned(p_shl_fu_346_p3) + unsigned(zext_ln139_fu_343_p1));
    add_ln139_fu_434_p2 <= std_logic_vector(unsigned(select_ln138_fu_416_p3) + unsigned(ap_const_lv9_5));
    add_ln140_1_fu_312_p2 <= std_logic_vector(unsigned(add_ln140_3_fu_302_p2) + unsigned(zext_ln140_2_fu_308_p1));
    add_ln140_2_fu_362_p2 <= std_logic_vector(unsigned(add_ln139_2_fu_353_p2) + unsigned(zext_ln140_3_fu_359_p1));
    add_ln140_3_fu_302_p2 <= std_logic_vector(unsigned(zext_ln140_1_fu_298_p1) + unsigned(zext_ln140_fu_286_p1));
    add_ln140_fu_428_p2 <= std_logic_vector(unsigned(idx_1_mid2_fu_409_p3) + unsigned(ap_const_lv9_1));
    and_ln137_fu_246_p2 <= (xor_ln137_fu_235_p2 and icmp_ln139_fu_240_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln137_fu_168_p2)
    begin
        if (((icmp_ln137_fu_168_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten133_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten133_fu_82)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten133_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten133_load <= indvar_flatten133_fu_82;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten151_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten151_fu_94)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten151_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_indvar_flatten151_load <= indvar_flatten151_fu_94;
        end if; 
    end process;

    empty_fu_265_p2 <= (icmp_ln138_reg_543 or and_ln137_fu_246_p2);
    fc_in_address0 <= zext_ln139_1_fu_423_p1(9 - 1 downto 0);
    fc_in_ce0 <= fc_in_ce0_local;

    fc_in_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            fc_in_ce0_local <= ap_const_logic_1;
        else 
            fc_in_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    fc_in_d0 <= pool2_out_q0;
    fc_in_we0 <= fc_in_we0_local;

    fc_in_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            fc_in_we0_local <= ap_const_logic_1;
        else 
            fc_in_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln137_fu_168_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten151_load = ap_const_lv9_190) else "0";
    icmp_ln138_fu_183_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten133_load = ap_const_lv6_19) else "0";
    icmp_ln139_fu_240_p2 <= "1" when (j_fu_58 = ap_const_lv3_5) else "0";
    idx_1_mid2_fu_409_p3 <= 
        add_ln1393_fu_74 when (and_ln137_reg_554_pp0_iter2_reg(0) = '1') else 
        select_ln137_2_fu_395_p3;
    j_4_mid2_fu_270_p3 <= 
        ap_const_lv3_0 when (empty_fu_265_p2(0) = '1') else 
        j_fu_58;
    p_shl_fu_346_p3 <= (trunc_ln140_reg_570 & ap_const_lv2_0);
    pool2_out_address0 <= zext_ln140_4_fu_368_p1(9 - 1 downto 0);
    pool2_out_ce0 <= pool2_out_ce0_local;

    pool2_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            pool2_out_ce0_local <= ap_const_logic_1;
        else 
            pool2_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln137_1_fu_228_p3 <= 
        ap_const_lv3_0 when (icmp_ln138_reg_543(0) = '1') else 
        i_fu_78;
    select_ln137_2_fu_395_p3 <= 
        add_ln137_11_fu_66 when (icmp_ln138_reg_543_pp0_iter2_reg(0) = '1') else 
        idx_1_fu_62;
    select_ln137_3_fu_402_p3 <= 
        add_ln137_11_fu_66 when (icmp_ln138_reg_543_pp0_iter2_reg(0) = '1') else 
        indvars_iv172_fu_90;
    select_ln137_4_fu_252_p3 <= 
        add_ln137_fu_222_p2 when (icmp_ln138_reg_543(0) = '1') else 
        c_fu_86;
    select_ln137_fu_388_p3 <= 
        add_ln137_11_fu_66 when (icmp_ln138_reg_543_pp0_iter2_reg(0) = '1') else 
        idx_fu_70;
    select_ln138_1_fu_278_p3 <= 
        add_ln138_fu_259_p2 when (and_ln137_fu_246_p2(0) = '1') else 
        select_ln137_1_fu_228_p3;
    select_ln138_2_fu_195_p3 <= 
        ap_const_lv6_1 when (icmp_ln138_fu_183_p2(0) = '1') else 
        add_ln138_1_fu_189_p2;
    select_ln138_fu_416_p3 <= 
        add_ln1393_fu_74 when (and_ln137_reg_554_pp0_iter2_reg(0) = '1') else 
        select_ln137_fu_388_p3;
    tmp_fu_290_p3 <= (select_ln137_4_fu_252_p3 & ap_const_lv2_0);
    trunc_ln140_fu_318_p1 <= add_ln140_1_fu_312_p2(7 - 1 downto 0);
    xor_ln137_fu_235_p2 <= (icmp_ln138_reg_543 xor ap_const_lv1_1);
    zext_ln139_1_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_1_mid2_fu_409_p3),64));
    zext_ln139_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln140_1_reg_565),9));
    zext_ln140_1_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_290_p3),8));
    zext_ln140_2_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln138_1_fu_278_p3),8));
    zext_ln140_3_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_4_mid2_reg_560),9));
    zext_ln140_4_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln140_2_fu_362_p2),64));
    zext_ln140_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln137_4_fu_252_p3),8));
end behav;
