// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module conv2d_conv2d_Pipeline_VITIS_LOOP_116_17_VITIS_LOOP_117_18_VITIS_LOOP_118_19 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv2_out_address0,
        conv2_out_ce0,
        conv2_out_q0,
        conv2_out_address1,
        conv2_out_ce1,
        conv2_out_q1,
        conv2_out_1_address0,
        conv2_out_1_ce0,
        conv2_out_1_q0,
        conv2_out_1_address1,
        conv2_out_1_ce1,
        conv2_out_1_q1,
        pool2_out_address0,
        pool2_out_ce0,
        pool2_out_we0,
        pool2_out_d0,
        grp_fu_1043_p_din0,
        grp_fu_1043_p_din1,
        grp_fu_1043_p_opcode,
        grp_fu_1043_p_dout0,
        grp_fu_1043_p_ce,
        grp_fu_1047_p_din0,
        grp_fu_1047_p_din1,
        grp_fu_1047_p_opcode,
        grp_fu_1047_p_dout0,
        grp_fu_1047_p_ce,
        grp_fu_1051_p_din0,
        grp_fu_1051_p_din1,
        grp_fu_1051_p_opcode,
        grp_fu_1051_p_dout0,
        grp_fu_1051_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] conv2_out_address0;
output   conv2_out_ce0;
input  [31:0] conv2_out_q0;
output  [10:0] conv2_out_address1;
output   conv2_out_ce1;
input  [31:0] conv2_out_q1;
output  [10:0] conv2_out_1_address0;
output   conv2_out_1_ce0;
input  [31:0] conv2_out_1_q0;
output  [10:0] conv2_out_1_address1;
output   conv2_out_1_ce1;
input  [31:0] conv2_out_1_q1;
output  [8:0] pool2_out_address0;
output   pool2_out_ce0;
output   pool2_out_we0;
output  [31:0] pool2_out_d0;
output  [31:0] grp_fu_1043_p_din0;
output  [31:0] grp_fu_1043_p_din1;
output  [4:0] grp_fu_1043_p_opcode;
input  [0:0] grp_fu_1043_p_dout0;
output   grp_fu_1043_p_ce;
output  [31:0] grp_fu_1047_p_din0;
output  [31:0] grp_fu_1047_p_din1;
output  [4:0] grp_fu_1047_p_opcode;
input  [0:0] grp_fu_1047_p_dout0;
output   grp_fu_1047_p_ce;
output  [31:0] grp_fu_1051_p_din0;
output  [31:0] grp_fu_1051_p_din1;
output  [4:0] grp_fu_1051_p_opcode;
input  [0:0] grp_fu_1051_p_dout0;
output   grp_fu_1051_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln116_fu_199_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln117_fu_223_p2;
reg   [0:0] icmp_ln117_reg_830;
wire   [4:0] select_ln116_1_fu_229_p3;
reg   [4:0] select_ln116_1_reg_837;
reg   [4:0] select_ln116_1_reg_837_pp0_iter1_reg;
wire   [2:0] j_3_mid2_fu_307_p3;
reg   [2:0] j_3_mid2_reg_844;
reg   [2:0] j_3_mid2_reg_844_pp0_iter2_reg;
wire   [2:0] select_ln117_fu_315_p3;
reg   [2:0] select_ln117_reg_850;
wire   [8:0] mul_ln120_fu_326_p2;
reg   [8:0] mul_ln120_reg_856;
wire   [8:0] add_ln120_fu_344_p2;
reg   [8:0] add_ln120_reg_861;
wire   [7:0] trunc_ln120_fu_350_p1;
reg   [7:0] trunc_ln120_reg_866;
wire   [7:0] add_ln127_fu_393_p2;
reg   [7:0] add_ln127_reg_871;
wire   [6:0] trunc_ln127_fu_399_p1;
reg   [6:0] trunc_ln127_reg_876;
wire   [10:0] add_ln124_1_fu_488_p2;
reg   [10:0] add_ln124_1_reg_886;
reg   [10:0] add_ln124_1_reg_886_pp0_iter3_reg;
wire   [8:0] add_ln127_1_fu_513_p2;
reg   [8:0] add_ln127_1_reg_896;
reg   [8:0] add_ln127_1_reg_896_pp0_iter4_reg;
reg   [8:0] add_ln127_1_reg_896_pp0_iter5_reg;
reg   [8:0] add_ln127_1_reg_896_pp0_iter6_reg;
reg   [8:0] add_ln127_1_reg_896_pp0_iter7_reg;
reg   [8:0] add_ln127_1_reg_896_pp0_iter8_reg;
reg   [8:0] add_ln127_1_reg_896_pp0_iter9_reg;
reg   [31:0] m_reg_901;
reg   [31:0] m_reg_901_pp0_iter4_reg;
reg   [31:0] m_7_reg_908;
reg   [31:0] m_7_reg_908_pp0_iter4_reg;
wire   [63:0] zext_ln124_2_fu_519_p1;
reg   [63:0] zext_ln124_2_reg_915;
reg   [63:0] zext_ln124_2_reg_915_pp0_iter5_reg;
wire   [31:0] m_8_fu_605_p3;
reg   [31:0] m_8_reg_925;
reg   [31:0] m_8_reg_925_pp0_iter6_reg;
reg   [31:0] m_9_reg_932;
reg   [31:0] m_9_reg_932_pp0_iter6_reg;
wire   [31:0] m_10_fu_693_p3;
reg   [31:0] m_10_reg_944;
reg   [31:0] m_10_reg_944_pp0_iter8_reg;
reg   [31:0] m_11_reg_951;
reg   [31:0] m_11_reg_951_pp0_iter8_reg;
wire   [31:0] m_12_fu_781_p3;
reg   [31:0] m_12_reg_958;
wire   [63:0] zext_ln120_7_fu_482_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln127_2_fu_787_p1;
reg   [2:0] j_fu_76;
wire   [2:0] add_ln118_fu_354_p2;
wire    ap_loop_init;
reg   [2:0] i_fu_80;
reg   [5:0] indvar_flatten113_fu_84;
wire   [5:0] select_ln117_1_fu_243_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten113_load;
reg   [4:0] c_fu_88;
reg   [4:0] ap_sig_allocacmp_c_load;
reg   [8:0] indvar_flatten126_fu_92;
wire   [8:0] add_ln116_1_fu_205_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten126_load;
reg    conv2_out_ce1_local;
reg    conv2_out_ce0_local;
reg    conv2_out_1_ce1_local;
reg    conv2_out_1_ce0_local;
reg    pool2_out_we0_local;
reg    pool2_out_ce0_local;
wire   [4:0] add_ln116_fu_217_p2;
wire   [5:0] add_ln117_1_fu_237_p2;
wire   [0:0] icmp_ln118_fu_284_p2;
wire   [0:0] xor_ln116_fu_279_p2;
wire   [2:0] select_ln116_fu_272_p3;
wire   [0:0] and_ln116_fu_290_p2;
wire   [0:0] empty_fu_302_p2;
wire   [2:0] add_ln117_fu_296_p2;
wire   [4:0] mul_ln120_fu_326_p0;
wire   [4:0] mul_ln120_fu_326_p1;
wire   [3:0] shl_ln2_fu_332_p3;
wire   [8:0] zext_ln120_3_fu_340_p1;
wire   [6:0] tmp_fu_373_p3;
wire   [7:0] zext_ln127_fu_380_p1;
wire   [7:0] zext_ln120_fu_370_p1;
wire   [7:0] add_ln127_2_fu_384_p2;
wire   [7:0] zext_ln127_1_fu_390_p1;
wire   [9:0] tmp_3_fu_403_p3;
wire   [10:0] tmp_4_fu_410_p3;
wire   [10:0] zext_ln120_4_fu_417_p1;
wire   [3:0] or_ln1_fu_427_p3;
wire   [8:0] zext_ln124_fu_434_p1;
wire   [8:0] add_ln124_fu_438_p2;
wire   [7:0] trunc_ln124_fu_443_p1;
wire   [9:0] tmp_5_fu_447_p3;
wire   [10:0] tmp_6_fu_455_p3;
wire   [10:0] zext_ln124_1_fu_463_p1;
wire   [10:0] sub_ln124_fu_421_p2;
wire   [10:0] zext_ln120_6_fu_473_p1;
wire   [10:0] add_ln120_1_fu_476_p2;
wire   [10:0] sub_ln118_fu_467_p2;
wire   [8:0] p_shl_fu_497_p3;
wire   [8:0] zext_ln120_2_fu_494_p1;
wire   [8:0] add_ln120_2_fu_504_p2;
wire   [8:0] zext_ln120_5_fu_510_p1;
wire   [31:0] bitcast_ln124_fu_523_p1;
wire   [31:0] bitcast_ln124_1_fu_540_p1;
wire   [7:0] tmp_s_fu_526_p4;
wire   [22:0] trunc_ln124_1_fu_536_p1;
wire   [0:0] icmp_ln124_1_fu_563_p2;
wire   [0:0] icmp_ln124_fu_557_p2;
wire   [7:0] tmp_2_fu_543_p4;
wire   [22:0] trunc_ln124_2_fu_553_p1;
wire   [0:0] icmp_ln124_3_fu_581_p2;
wire   [0:0] icmp_ln124_2_fu_575_p2;
wire   [0:0] or_ln124_fu_569_p2;
wire   [0:0] or_ln124_1_fu_587_p2;
wire   [0:0] and_ln124_fu_593_p2;
wire   [0:0] and_ln124_1_fu_599_p2;
wire   [31:0] bitcast_ln124_2_fu_611_p1;
wire   [31:0] bitcast_ln124_3_fu_628_p1;
wire   [7:0] tmp_8_fu_614_p4;
wire   [22:0] trunc_ln124_3_fu_624_p1;
wire   [0:0] icmp_ln124_5_fu_651_p2;
wire   [0:0] icmp_ln124_4_fu_645_p2;
wire   [7:0] tmp_9_fu_631_p4;
wire   [22:0] trunc_ln124_4_fu_641_p1;
wire   [0:0] icmp_ln124_7_fu_669_p2;
wire   [0:0] icmp_ln124_6_fu_663_p2;
wire   [0:0] or_ln124_2_fu_657_p2;
wire   [0:0] or_ln124_3_fu_675_p2;
wire   [0:0] and_ln124_2_fu_681_p2;
wire   [0:0] and_ln124_3_fu_687_p2;
wire   [31:0] bitcast_ln124_4_fu_699_p1;
wire   [31:0] bitcast_ln124_5_fu_716_p1;
wire   [7:0] tmp_11_fu_702_p4;
wire   [22:0] trunc_ln124_5_fu_712_p1;
wire   [0:0] icmp_ln124_9_fu_739_p2;
wire   [0:0] icmp_ln124_8_fu_733_p2;
wire   [7:0] tmp_12_fu_719_p4;
wire   [22:0] trunc_ln124_6_fu_729_p1;
wire   [0:0] icmp_ln124_11_fu_757_p2;
wire   [0:0] icmp_ln124_10_fu_751_p2;
wire   [0:0] or_ln124_4_fu_745_p2;
wire   [0:0] or_ln124_5_fu_763_p2;
wire   [0:0] and_ln124_4_fu_769_p2;
wire   [0:0] and_ln124_5_fu_775_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [8:0] mul_ln120_fu_326_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 j_fu_76 = 3'd0;
#0 i_fu_80 = 3'd0;
#0 indvar_flatten113_fu_84 = 6'd0;
#0 c_fu_88 = 5'd0;
#0 indvar_flatten126_fu_92 = 9'd0;
#0 ap_done_reg = 1'b0;
end

conv2d_mul_5ns_5ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 9 ))
mul_5ns_5ns_9_1_1_U52(
    .din0(mul_ln120_fu_326_p0),
    .din1(mul_ln120_fu_326_p1),
    .dout(mul_ln120_fu_326_p2)
);

conv2d_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln116_fu_199_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_88 <= select_ln116_1_fu_229_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_88 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_80 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_80 <= select_ln117_fu_315_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln116_fu_199_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten113_fu_84 <= select_ln117_1_fu_243_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten113_fu_84 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln116_fu_199_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten126_fu_92 <= add_ln116_1_fu_205_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten126_fu_92 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_76 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_76 <= add_ln118_fu_354_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln120_reg_861 <= add_ln120_fu_344_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln117_reg_830 <= icmp_ln117_fu_223_p2;
        j_3_mid2_reg_844 <= j_3_mid2_fu_307_p3;
        mul_ln120_reg_856 <= mul_ln120_fu_326_p2;
        select_ln116_1_reg_837 <= select_ln116_1_fu_229_p3;
        select_ln116_1_reg_837_pp0_iter1_reg <= select_ln116_1_reg_837;
        select_ln117_reg_850 <= select_ln117_fu_315_p3;
        trunc_ln120_reg_866 <= trunc_ln120_fu_350_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln124_1_reg_886 <= add_ln124_1_fu_488_p2;
        add_ln124_1_reg_886_pp0_iter3_reg <= add_ln124_1_reg_886;
        add_ln127_1_reg_896 <= add_ln127_1_fu_513_p2;
        add_ln127_1_reg_896_pp0_iter4_reg <= add_ln127_1_reg_896;
        add_ln127_1_reg_896_pp0_iter5_reg <= add_ln127_1_reg_896_pp0_iter4_reg;
        add_ln127_1_reg_896_pp0_iter6_reg <= add_ln127_1_reg_896_pp0_iter5_reg;
        add_ln127_1_reg_896_pp0_iter7_reg <= add_ln127_1_reg_896_pp0_iter6_reg;
        add_ln127_1_reg_896_pp0_iter8_reg <= add_ln127_1_reg_896_pp0_iter7_reg;
        add_ln127_1_reg_896_pp0_iter9_reg <= add_ln127_1_reg_896_pp0_iter8_reg;
        add_ln127_reg_871 <= add_ln127_fu_393_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        j_3_mid2_reg_844_pp0_iter2_reg <= j_3_mid2_reg_844;
        m_10_reg_944 <= m_10_fu_693_p3;
        m_10_reg_944_pp0_iter8_reg <= m_10_reg_944;
        m_11_reg_951_pp0_iter8_reg <= m_11_reg_951;
        m_12_reg_958 <= m_12_fu_781_p3;
        m_7_reg_908_pp0_iter4_reg <= m_7_reg_908;
        m_8_reg_925 <= m_8_fu_605_p3;
        m_8_reg_925_pp0_iter6_reg <= m_8_reg_925;
        m_9_reg_932_pp0_iter6_reg <= m_9_reg_932;
        m_reg_901_pp0_iter4_reg <= m_reg_901;
        trunc_ln127_reg_876 <= trunc_ln127_fu_399_p1;
        zext_ln124_2_reg_915[10 : 0] <= zext_ln124_2_fu_519_p1[10 : 0];
        zext_ln124_2_reg_915_pp0_iter5_reg[10 : 0] <= zext_ln124_2_reg_915[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        m_11_reg_951 <= conv2_out_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        m_7_reg_908 <= conv2_out_1_q1;
        m_reg_901 <= conv2_out_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        m_9_reg_932 <= conv2_out_q0;
    end
end

always @ (*) begin
    if (((icmp_ln116_fu_199_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 5'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten113_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten113_load = indvar_flatten113_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten126_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten126_load = indvar_flatten126_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        conv2_out_1_ce0_local = 1'b1;
    end else begin
        conv2_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv2_out_1_ce1_local = 1'b1;
    end else begin
        conv2_out_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        conv2_out_ce0_local = 1'b1;
    end else begin
        conv2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        conv2_out_ce1_local = 1'b1;
    end else begin
        conv2_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        pool2_out_ce0_local = 1'b1;
    end else begin
        pool2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        pool2_out_we0_local = 1'b1;
    end else begin
        pool2_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln116_1_fu_205_p2 = (ap_sig_allocacmp_indvar_flatten126_load + 9'd1);

assign add_ln116_fu_217_p2 = (ap_sig_allocacmp_c_load + 5'd1);

assign add_ln117_1_fu_237_p2 = (ap_sig_allocacmp_indvar_flatten113_load + 6'd1);

assign add_ln117_fu_296_p2 = (select_ln116_fu_272_p3 + 3'd1);

assign add_ln118_fu_354_p2 = (j_3_mid2_fu_307_p3 + 3'd1);

assign add_ln120_1_fu_476_p2 = (sub_ln124_fu_421_p2 + zext_ln120_6_fu_473_p1);

assign add_ln120_2_fu_504_p2 = (p_shl_fu_497_p3 + zext_ln120_2_fu_494_p1);

assign add_ln120_fu_344_p2 = (mul_ln120_fu_326_p2 + zext_ln120_3_fu_340_p1);

assign add_ln124_1_fu_488_p2 = (sub_ln118_fu_467_p2 + zext_ln120_6_fu_473_p1);

assign add_ln124_fu_438_p2 = (mul_ln120_reg_856 + zext_ln124_fu_434_p1);

assign add_ln127_1_fu_513_p2 = (add_ln120_2_fu_504_p2 + zext_ln120_5_fu_510_p1);

assign add_ln127_2_fu_384_p2 = (zext_ln127_fu_380_p1 + zext_ln120_fu_370_p1);

assign add_ln127_fu_393_p2 = (add_ln127_2_fu_384_p2 + zext_ln127_1_fu_390_p1);

assign and_ln116_fu_290_p2 = (xor_ln116_fu_279_p2 & icmp_ln118_fu_284_p2);

assign and_ln124_1_fu_599_p2 = (grp_fu_1043_p_dout0 & and_ln124_fu_593_p2);

assign and_ln124_2_fu_681_p2 = (or_ln124_3_fu_675_p2 & or_ln124_2_fu_657_p2);

assign and_ln124_3_fu_687_p2 = (grp_fu_1047_p_dout0 & and_ln124_2_fu_681_p2);

assign and_ln124_4_fu_769_p2 = (or_ln124_5_fu_763_p2 & or_ln124_4_fu_745_p2);

assign and_ln124_5_fu_775_p2 = (grp_fu_1051_p_dout0 & and_ln124_4_fu_769_p2);

assign and_ln124_fu_593_p2 = (or_ln124_fu_569_p2 & or_ln124_1_fu_587_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln124_1_fu_540_p1 = m_reg_901_pp0_iter4_reg;

assign bitcast_ln124_2_fu_611_p1 = m_9_reg_932_pp0_iter6_reg;

assign bitcast_ln124_3_fu_628_p1 = m_8_reg_925_pp0_iter6_reg;

assign bitcast_ln124_4_fu_699_p1 = m_11_reg_951_pp0_iter8_reg;

assign bitcast_ln124_5_fu_716_p1 = m_10_reg_944_pp0_iter8_reg;

assign bitcast_ln124_fu_523_p1 = m_7_reg_908_pp0_iter4_reg;

assign conv2_out_1_address0 = zext_ln124_2_reg_915_pp0_iter5_reg;

assign conv2_out_1_address1 = zext_ln120_7_fu_482_p1;

assign conv2_out_1_ce0 = conv2_out_1_ce0_local;

assign conv2_out_1_ce1 = conv2_out_1_ce1_local;

assign conv2_out_address0 = zext_ln124_2_fu_519_p1;

assign conv2_out_address1 = zext_ln120_7_fu_482_p1;

assign conv2_out_ce0 = conv2_out_ce0_local;

assign conv2_out_ce1 = conv2_out_ce1_local;

assign empty_fu_302_p2 = (icmp_ln117_reg_830 | and_ln116_fu_290_p2);

assign grp_fu_1043_p_ce = 1'b1;

assign grp_fu_1043_p_din0 = m_7_reg_908;

assign grp_fu_1043_p_din1 = m_reg_901;

assign grp_fu_1043_p_opcode = 5'd2;

assign grp_fu_1047_p_ce = 1'b1;

assign grp_fu_1047_p_din0 = m_9_reg_932;

assign grp_fu_1047_p_din1 = m_8_reg_925;

assign grp_fu_1047_p_opcode = 5'd2;

assign grp_fu_1051_p_ce = 1'b1;

assign grp_fu_1051_p_din0 = m_11_reg_951;

assign grp_fu_1051_p_din1 = m_10_reg_944;

assign grp_fu_1051_p_opcode = 5'd2;

assign icmp_ln116_fu_199_p2 = ((ap_sig_allocacmp_indvar_flatten126_load == 9'd400) ? 1'b1 : 1'b0);

assign icmp_ln117_fu_223_p2 = ((ap_sig_allocacmp_indvar_flatten113_load == 6'd25) ? 1'b1 : 1'b0);

assign icmp_ln118_fu_284_p2 = ((j_fu_76 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln124_10_fu_751_p2 = ((tmp_12_fu_719_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln124_11_fu_757_p2 = ((trunc_ln124_6_fu_729_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln124_1_fu_563_p2 = ((trunc_ln124_1_fu_536_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln124_2_fu_575_p2 = ((tmp_2_fu_543_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln124_3_fu_581_p2 = ((trunc_ln124_2_fu_553_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln124_4_fu_645_p2 = ((tmp_8_fu_614_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln124_5_fu_651_p2 = ((trunc_ln124_3_fu_624_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln124_6_fu_663_p2 = ((tmp_9_fu_631_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln124_7_fu_669_p2 = ((trunc_ln124_4_fu_641_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln124_8_fu_733_p2 = ((tmp_11_fu_702_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln124_9_fu_739_p2 = ((trunc_ln124_5_fu_712_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln124_fu_557_p2 = ((tmp_s_fu_526_p4 != 8'd255) ? 1'b1 : 1'b0);

assign j_3_mid2_fu_307_p3 = ((empty_fu_302_p2[0:0] == 1'b1) ? 3'd0 : j_fu_76);

assign m_10_fu_693_p3 = ((and_ln124_3_fu_687_p2[0:0] == 1'b1) ? m_9_reg_932_pp0_iter6_reg : m_8_reg_925_pp0_iter6_reg);

assign m_12_fu_781_p3 = ((and_ln124_5_fu_775_p2[0:0] == 1'b1) ? m_11_reg_951_pp0_iter8_reg : m_10_reg_944_pp0_iter8_reg);

assign m_8_fu_605_p3 = ((and_ln124_1_fu_599_p2[0:0] == 1'b1) ? m_7_reg_908_pp0_iter4_reg : m_reg_901_pp0_iter4_reg);

assign mul_ln120_fu_326_p0 = mul_ln120_fu_326_p00;

assign mul_ln120_fu_326_p00 = select_ln116_1_reg_837;

assign mul_ln120_fu_326_p1 = 9'd11;

assign or_ln124_1_fu_587_p2 = (icmp_ln124_3_fu_581_p2 | icmp_ln124_2_fu_575_p2);

assign or_ln124_2_fu_657_p2 = (icmp_ln124_5_fu_651_p2 | icmp_ln124_4_fu_645_p2);

assign or_ln124_3_fu_675_p2 = (icmp_ln124_7_fu_669_p2 | icmp_ln124_6_fu_663_p2);

assign or_ln124_4_fu_745_p2 = (icmp_ln124_9_fu_739_p2 | icmp_ln124_8_fu_733_p2);

assign or_ln124_5_fu_763_p2 = (icmp_ln124_11_fu_757_p2 | icmp_ln124_10_fu_751_p2);

assign or_ln124_fu_569_p2 = (icmp_ln124_fu_557_p2 | icmp_ln124_1_fu_563_p2);

assign or_ln1_fu_427_p3 = {{select_ln117_reg_850}, {1'd1}};

assign p_shl_fu_497_p3 = {{trunc_ln127_reg_876}, {2'd0}};

assign pool2_out_address0 = zext_ln127_2_fu_787_p1;

assign pool2_out_ce0 = pool2_out_ce0_local;

assign pool2_out_d0 = m_12_reg_958;

assign pool2_out_we0 = pool2_out_we0_local;

assign select_ln116_1_fu_229_p3 = ((icmp_ln117_fu_223_p2[0:0] == 1'b1) ? add_ln116_fu_217_p2 : ap_sig_allocacmp_c_load);

assign select_ln116_fu_272_p3 = ((icmp_ln117_reg_830[0:0] == 1'b1) ? 3'd0 : i_fu_80);

assign select_ln117_1_fu_243_p3 = ((icmp_ln117_fu_223_p2[0:0] == 1'b1) ? 6'd1 : add_ln117_1_fu_237_p2);

assign select_ln117_fu_315_p3 = ((and_ln116_fu_290_p2[0:0] == 1'b1) ? add_ln117_fu_296_p2 : select_ln116_fu_272_p3);

assign shl_ln2_fu_332_p3 = {{select_ln117_fu_315_p3}, {1'd0}};

assign sub_ln118_fu_467_p2 = (tmp_6_fu_455_p3 - zext_ln124_1_fu_463_p1);

assign sub_ln124_fu_421_p2 = (tmp_4_fu_410_p3 - zext_ln120_4_fu_417_p1);

assign tmp_11_fu_702_p4 = {{bitcast_ln124_4_fu_699_p1[30:23]}};

assign tmp_12_fu_719_p4 = {{bitcast_ln124_5_fu_716_p1[30:23]}};

assign tmp_2_fu_543_p4 = {{bitcast_ln124_1_fu_540_p1[30:23]}};

assign tmp_3_fu_403_p3 = {{add_ln120_reg_861}, {1'd0}};

assign tmp_4_fu_410_p3 = {{trunc_ln120_reg_866}, {3'd0}};

assign tmp_5_fu_447_p3 = {{add_ln124_fu_438_p2}, {1'd0}};

assign tmp_6_fu_455_p3 = {{trunc_ln124_fu_443_p1}, {3'd0}};

assign tmp_8_fu_614_p4 = {{bitcast_ln124_2_fu_611_p1[30:23]}};

assign tmp_9_fu_631_p4 = {{bitcast_ln124_3_fu_628_p1[30:23]}};

assign tmp_fu_373_p3 = {{select_ln116_1_reg_837_pp0_iter1_reg}, {2'd0}};

assign tmp_s_fu_526_p4 = {{bitcast_ln124_fu_523_p1[30:23]}};

assign trunc_ln120_fu_350_p1 = add_ln120_fu_344_p2[7:0];

assign trunc_ln124_1_fu_536_p1 = bitcast_ln124_fu_523_p1[22:0];

assign trunc_ln124_2_fu_553_p1 = bitcast_ln124_1_fu_540_p1[22:0];

assign trunc_ln124_3_fu_624_p1 = bitcast_ln124_2_fu_611_p1[22:0];

assign trunc_ln124_4_fu_641_p1 = bitcast_ln124_3_fu_628_p1[22:0];

assign trunc_ln124_5_fu_712_p1 = bitcast_ln124_4_fu_699_p1[22:0];

assign trunc_ln124_6_fu_729_p1 = bitcast_ln124_5_fu_716_p1[22:0];

assign trunc_ln124_fu_443_p1 = add_ln124_fu_438_p2[7:0];

assign trunc_ln127_fu_399_p1 = add_ln127_fu_393_p2[6:0];

assign xor_ln116_fu_279_p2 = (icmp_ln117_reg_830 ^ 1'd1);

assign zext_ln120_2_fu_494_p1 = add_ln127_reg_871;

assign zext_ln120_3_fu_340_p1 = shl_ln2_fu_332_p3;

assign zext_ln120_4_fu_417_p1 = tmp_3_fu_403_p3;

assign zext_ln120_5_fu_510_p1 = j_3_mid2_reg_844_pp0_iter2_reg;

assign zext_ln120_6_fu_473_p1 = j_3_mid2_reg_844;

assign zext_ln120_7_fu_482_p1 = add_ln120_1_fu_476_p2;

assign zext_ln120_fu_370_p1 = select_ln116_1_reg_837_pp0_iter1_reg;

assign zext_ln124_1_fu_463_p1 = tmp_5_fu_447_p3;

assign zext_ln124_2_fu_519_p1 = add_ln124_1_reg_886_pp0_iter3_reg;

assign zext_ln124_fu_434_p1 = or_ln1_fu_427_p3;

assign zext_ln127_1_fu_390_p1 = select_ln117_reg_850;

assign zext_ln127_2_fu_787_p1 = add_ln127_1_reg_896_pp0_iter9_reg;

assign zext_ln127_fu_380_p1 = tmp_fu_373_p3;

always @ (posedge ap_clk) begin
    zext_ln124_2_reg_915[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln124_2_reg_915_pp0_iter5_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //conv2d_conv2d_Pipeline_VITIS_LOOP_116_17_VITIS_LOOP_117_18_VITIS_LOOP_118_19
