// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module conv2d_conv2d_Pipeline_VITIS_LOOP_60_6_VITIS_LOOP_61_7_VITIS_LOOP_62_8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv1_out_address0,
        conv1_out_ce0,
        conv1_out_q0,
        conv1_out_address1,
        conv1_out_ce1,
        conv1_out_q1,
        conv1_out_1_address0,
        conv1_out_1_ce0,
        conv1_out_1_q0,
        conv1_out_1_address1,
        conv1_out_1_ce1,
        conv1_out_1_q1,
        pool1_out_address0,
        pool1_out_ce0,
        pool1_out_we0,
        pool1_out_d0,
        grp_fu_1043_p_din0,
        grp_fu_1043_p_din1,
        grp_fu_1043_p_opcode,
        grp_fu_1043_p_dout0,
        grp_fu_1043_p_ce,
        grp_fu_1047_p_din0,
        grp_fu_1047_p_din1,
        grp_fu_1047_p_opcode,
        grp_fu_1047_p_dout0,
        grp_fu_1047_p_ce,
        grp_fu_1051_p_din0,
        grp_fu_1051_p_din1,
        grp_fu_1051_p_opcode,
        grp_fu_1051_p_dout0,
        grp_fu_1051_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] conv1_out_address0;
output   conv1_out_ce0;
input  [31:0] conv1_out_q0;
output  [11:0] conv1_out_address1;
output   conv1_out_ce1;
input  [31:0] conv1_out_q1;
output  [11:0] conv1_out_1_address0;
output   conv1_out_1_ce0;
input  [31:0] conv1_out_1_q0;
output  [11:0] conv1_out_1_address1;
output   conv1_out_1_ce1;
input  [31:0] conv1_out_1_q1;
output  [10:0] pool1_out_address0;
output   pool1_out_ce0;
output   pool1_out_we0;
output  [31:0] pool1_out_d0;
output  [31:0] grp_fu_1043_p_din0;
output  [31:0] grp_fu_1043_p_din1;
output  [4:0] grp_fu_1043_p_opcode;
input  [0:0] grp_fu_1043_p_dout0;
output   grp_fu_1043_p_ce;
output  [31:0] grp_fu_1047_p_din0;
output  [31:0] grp_fu_1047_p_din1;
output  [4:0] grp_fu_1047_p_opcode;
input  [0:0] grp_fu_1047_p_dout0;
output   grp_fu_1047_p_ce;
output  [31:0] grp_fu_1051_p_din0;
output  [31:0] grp_fu_1051_p_din1;
output  [4:0] grp_fu_1051_p_opcode;
input  [0:0] grp_fu_1051_p_dout0;
output   grp_fu_1051_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln60_fu_191_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln61_fu_215_p2;
reg   [0:0] icmp_ln61_reg_749;
wire   [3:0] select_ln60_1_fu_221_p3;
reg   [3:0] select_ln60_1_reg_756;
wire   [3:0] j_1_mid2_fu_299_p3;
reg   [3:0] j_1_mid2_reg_762;
reg   [3:0] j_1_mid2_reg_762_pp0_iter2_reg;
reg   [3:0] j_1_mid2_reg_762_pp0_iter3_reg;
reg   [3:0] j_1_mid2_reg_762_pp0_iter4_reg;
reg   [3:0] j_1_mid2_reg_762_pp0_iter5_reg;
wire   [3:0] select_ln61_fu_307_p3;
reg   [3:0] select_ln61_reg_768;
reg   [3:0] select_ln61_reg_768_pp0_iter2_reg;
wire   [11:0] zext_ln64_5_fu_390_p1;
wire   [11:0] grp_fu_694_p3;
reg   [11:0] add_ln68_1_reg_809;
reg   [11:0] add_ln68_1_reg_809_pp0_iter5_reg;
reg   [31:0] m_reg_819;
reg   [31:0] m_reg_819_pp0_iter6_reg;
reg   [31:0] m_1_reg_826;
reg   [31:0] m_1_reg_826_pp0_iter6_reg;
wire   [63:0] zext_ln68_2_fu_404_p1;
reg   [63:0] zext_ln68_2_reg_838;
reg   [63:0] zext_ln68_2_reg_838_pp0_iter7_reg;
wire   [10:0] grp_fu_702_p3;
reg   [10:0] add_ln71_1_reg_848;
reg   [10:0] add_ln71_1_reg_848_pp0_iter8_reg;
reg   [10:0] add_ln71_1_reg_848_pp0_iter9_reg;
reg   [10:0] add_ln71_1_reg_848_pp0_iter10_reg;
reg   [10:0] add_ln71_1_reg_848_pp0_iter11_reg;
wire   [31:0] m_2_fu_490_p3;
reg   [31:0] m_2_reg_853;
reg   [31:0] m_2_reg_853_pp0_iter8_reg;
reg   [31:0] m_3_reg_860;
reg   [31:0] m_3_reg_860_pp0_iter8_reg;
wire   [31:0] m_4_fu_578_p3;
reg   [31:0] m_4_reg_872;
reg   [31:0] m_4_reg_872_pp0_iter10_reg;
reg   [31:0] m_5_reg_879;
reg   [31:0] m_5_reg_879_pp0_iter10_reg;
wire   [31:0] m_6_fu_666_p3;
reg   [31:0] m_6_reg_886;
wire   [63:0] zext_ln64_6_fu_396_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln71_1_fu_672_p1;
reg   [3:0] j_fu_68;
wire   [3:0] add_ln62_fu_371_p2;
wire    ap_loop_init;
reg   [3:0] i_fu_72;
reg   [7:0] indvar_flatten9_fu_76;
wire   [7:0] select_ln61_1_fu_235_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten9_load;
reg   [3:0] c_fu_80;
reg   [3:0] ap_sig_allocacmp_c_load;
reg   [10:0] indvar_flatten22_fu_84;
wire   [10:0] add_ln60_1_fu_197_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten22_load;
reg    conv1_out_ce1_local;
reg    conv1_out_ce0_local;
reg    conv1_out_1_ce1_local;
reg    conv1_out_1_ce0_local;
reg    pool1_out_we0_local;
reg    pool1_out_ce0_local;
wire   [3:0] add_ln60_fu_209_p2;
wire   [7:0] add_ln61_1_fu_229_p2;
wire   [0:0] icmp_ln62_fu_276_p2;
wire   [0:0] xor_ln60_fu_271_p2;
wire   [3:0] select_ln60_fu_264_p3;
wire   [0:0] and_ln60_fu_282_p2;
wire   [0:0] empty_fu_294_p2;
wire   [3:0] add_ln61_fu_288_p2;
wire   [3:0] mul_ln64_fu_321_p0;
wire   [5:0] mul_ln64_fu_321_p1;
wire   [4:0] shl_ln_fu_327_p3;
wire   [8:0] mul_ln64_fu_321_p2;
wire   [8:0] zext_ln64_3_fu_335_p1;
wire   [8:0] add_ln64_fu_339_p2;
wire   [4:0] or_ln_fu_349_p3;
wire   [8:0] zext_ln68_1_fu_357_p1;
wire   [8:0] add_ln68_fu_361_p2;
wire   [7:0] grp_fu_676_p3;
wire   [11:0] grp_fu_685_p3;
wire   [31:0] bitcast_ln68_fu_408_p1;
wire   [31:0] bitcast_ln68_1_fu_425_p1;
wire   [7:0] tmp_2_fu_411_p4;
wire   [22:0] trunc_ln68_fu_421_p1;
wire   [0:0] icmp_ln68_1_fu_448_p2;
wire   [0:0] icmp_ln68_fu_442_p2;
wire   [7:0] tmp_3_fu_428_p4;
wire   [22:0] trunc_ln68_1_fu_438_p1;
wire   [0:0] icmp_ln68_3_fu_466_p2;
wire   [0:0] icmp_ln68_2_fu_460_p2;
wire   [0:0] or_ln68_fu_454_p2;
wire   [0:0] or_ln68_1_fu_472_p2;
wire   [0:0] and_ln68_fu_478_p2;
wire   [0:0] and_ln68_1_fu_484_p2;
wire   [31:0] bitcast_ln68_2_fu_496_p1;
wire   [31:0] bitcast_ln68_3_fu_513_p1;
wire   [7:0] tmp_5_fu_499_p4;
wire   [22:0] trunc_ln68_2_fu_509_p1;
wire   [0:0] icmp_ln68_5_fu_536_p2;
wire   [0:0] icmp_ln68_4_fu_530_p2;
wire   [7:0] tmp_6_fu_516_p4;
wire   [22:0] trunc_ln68_3_fu_526_p1;
wire   [0:0] icmp_ln68_7_fu_554_p2;
wire   [0:0] icmp_ln68_6_fu_548_p2;
wire   [0:0] or_ln68_2_fu_542_p2;
wire   [0:0] or_ln68_3_fu_560_p2;
wire   [0:0] and_ln68_2_fu_566_p2;
wire   [0:0] and_ln68_3_fu_572_p2;
wire   [31:0] bitcast_ln68_4_fu_584_p1;
wire   [31:0] bitcast_ln68_5_fu_601_p1;
wire   [7:0] tmp_8_fu_587_p4;
wire   [22:0] trunc_ln68_4_fu_597_p1;
wire   [0:0] icmp_ln68_9_fu_624_p2;
wire   [0:0] icmp_ln68_8_fu_618_p2;
wire   [7:0] tmp_9_fu_604_p4;
wire   [22:0] trunc_ln68_5_fu_614_p1;
wire   [0:0] icmp_ln68_11_fu_642_p2;
wire   [0:0] icmp_ln68_10_fu_636_p2;
wire   [0:0] or_ln68_4_fu_630_p2;
wire   [0:0] or_ln68_5_fu_648_p2;
wire   [0:0] and_ln68_4_fu_654_p2;
wire   [0:0] and_ln68_5_fu_660_p2;
wire   [3:0] grp_fu_676_p0;
wire   [3:0] grp_fu_676_p1;
wire   [3:0] grp_fu_676_p2;
wire   [8:0] grp_fu_685_p0;
wire   [3:0] grp_fu_685_p1;
wire   [3:0] grp_fu_685_p2;
wire   [8:0] grp_fu_694_p0;
wire   [3:0] grp_fu_694_p1;
wire   [3:0] grp_fu_694_p2;
wire   [7:0] grp_fu_702_p0;
wire   [3:0] grp_fu_702_p1;
wire   [3:0] grp_fu_702_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [7:0] grp_fu_676_p00;
wire   [7:0] grp_fu_676_p20;
wire   [11:0] grp_fu_685_p00;
wire   [11:0] grp_fu_694_p00;
wire   [10:0] grp_fu_702_p00;
wire   [10:0] grp_fu_702_p20;
wire   [8:0] mul_ln64_fu_321_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 j_fu_68 = 4'd0;
#0 i_fu_72 = 4'd0;
#0 indvar_flatten9_fu_76 = 8'd0;
#0 c_fu_80 = 4'd0;
#0 indvar_flatten22_fu_84 = 11'd0;
#0 ap_done_reg = 1'b0;
end

conv2d_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U25(
    .din0(mul_ln64_fu_321_p0),
    .din1(mul_ln64_fu_321_p1),
    .dout(mul_ln64_fu_321_p2)
);

conv2d_mac_muladd_4ns_4ns_4ns_8_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
mac_muladd_4ns_4ns_4ns_8_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_676_p0),
    .din1(grp_fu_676_p1),
    .din2(grp_fu_676_p2),
    .ce(1'b1),
    .dout(grp_fu_676_p3)
);

conv2d_mac_muladd_9ns_4ns_4ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
mac_muladd_9ns_4ns_4ns_12_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_685_p0),
    .din1(grp_fu_685_p1),
    .din2(grp_fu_685_p2),
    .ce(1'b1),
    .dout(grp_fu_685_p3)
);

conv2d_mac_muladd_9ns_4ns_4ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
mac_muladd_9ns_4ns_4ns_12_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_694_p0),
    .din1(grp_fu_694_p1),
    .din2(grp_fu_694_p2),
    .ce(1'b1),
    .dout(grp_fu_694_p3)
);

conv2d_mac_muladd_8ns_4ns_4ns_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mac_muladd_8ns_4ns_4ns_11_4_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_702_p0),
    .din1(grp_fu_702_p1),
    .din2(grp_fu_702_p2),
    .ce(1'b1),
    .dout(grp_fu_702_p3)
);

conv2d_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln60_fu_191_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_80 <= select_ln60_1_fu_221_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_80 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_72 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_72 <= select_ln61_fu_307_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln60_fu_191_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten22_fu_84 <= add_ln60_1_fu_197_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten22_fu_84 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln60_fu_191_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten9_fu_76 <= select_ln61_1_fu_235_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten9_fu_76 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_68 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_68 <= add_ln62_fu_371_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        add_ln68_1_reg_809 <= grp_fu_694_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln68_1_reg_809_pp0_iter5_reg <= add_ln68_1_reg_809;
        add_ln71_1_reg_848_pp0_iter10_reg <= add_ln71_1_reg_848_pp0_iter9_reg;
        add_ln71_1_reg_848_pp0_iter11_reg <= add_ln71_1_reg_848_pp0_iter10_reg;
        add_ln71_1_reg_848_pp0_iter8_reg <= add_ln71_1_reg_848;
        add_ln71_1_reg_848_pp0_iter9_reg <= add_ln71_1_reg_848_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        j_1_mid2_reg_762_pp0_iter2_reg <= j_1_mid2_reg_762;
        j_1_mid2_reg_762_pp0_iter3_reg <= j_1_mid2_reg_762_pp0_iter2_reg;
        j_1_mid2_reg_762_pp0_iter4_reg <= j_1_mid2_reg_762_pp0_iter3_reg;
        j_1_mid2_reg_762_pp0_iter5_reg <= j_1_mid2_reg_762_pp0_iter4_reg;
        m_1_reg_826_pp0_iter6_reg <= m_1_reg_826;
        m_2_reg_853 <= m_2_fu_490_p3;
        m_2_reg_853_pp0_iter8_reg <= m_2_reg_853;
        m_3_reg_860_pp0_iter8_reg <= m_3_reg_860;
        m_4_reg_872 <= m_4_fu_578_p3;
        m_4_reg_872_pp0_iter10_reg <= m_4_reg_872;
        m_5_reg_879_pp0_iter10_reg <= m_5_reg_879;
        m_6_reg_886 <= m_6_fu_666_p3;
        m_reg_819_pp0_iter6_reg <= m_reg_819;
        select_ln61_reg_768_pp0_iter2_reg <= select_ln61_reg_768;
        zext_ln68_2_reg_838[11 : 0] <= zext_ln68_2_fu_404_p1[11 : 0];
        zext_ln68_2_reg_838_pp0_iter7_reg[11 : 0] <= zext_ln68_2_reg_838[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        add_ln71_1_reg_848 <= grp_fu_702_p3;
        m_3_reg_860 <= conv1_out_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln61_reg_749 <= icmp_ln61_fu_215_p2;
        j_1_mid2_reg_762 <= j_1_mid2_fu_299_p3;
        select_ln60_1_reg_756 <= select_ln60_1_fu_221_p3;
        select_ln61_reg_768 <= select_ln61_fu_307_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        m_1_reg_826 <= conv1_out_1_q1;
        m_reg_819 <= conv1_out_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        m_5_reg_879 <= conv1_out_1_q0;
    end
end

always @ (*) begin
    if (((icmp_ln60_fu_191_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 4'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten22_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten22_load = indvar_flatten22_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten9_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten9_load = indvar_flatten9_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        conv1_out_1_ce0_local = 1'b1;
    end else begin
        conv1_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        conv1_out_1_ce1_local = 1'b1;
    end else begin
        conv1_out_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        conv1_out_ce0_local = 1'b1;
    end else begin
        conv1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        conv1_out_ce1_local = 1'b1;
    end else begin
        conv1_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        pool1_out_ce0_local = 1'b1;
    end else begin
        pool1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        pool1_out_we0_local = 1'b1;
    end else begin
        pool1_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln60_1_fu_197_p2 = (ap_sig_allocacmp_indvar_flatten22_load + 11'd1);

assign add_ln60_fu_209_p2 = (ap_sig_allocacmp_c_load + 4'd1);

assign add_ln61_1_fu_229_p2 = (ap_sig_allocacmp_indvar_flatten9_load + 8'd1);

assign add_ln61_fu_288_p2 = (select_ln60_fu_264_p3 + 4'd1);

assign add_ln62_fu_371_p2 = (j_1_mid2_fu_299_p3 + 4'd1);

assign add_ln64_fu_339_p2 = (mul_ln64_fu_321_p2 + zext_ln64_3_fu_335_p1);

assign add_ln68_fu_361_p2 = (mul_ln64_fu_321_p2 + zext_ln68_1_fu_357_p1);

assign and_ln60_fu_282_p2 = (xor_ln60_fu_271_p2 & icmp_ln62_fu_276_p2);

assign and_ln68_1_fu_484_p2 = (grp_fu_1043_p_dout0 & and_ln68_fu_478_p2);

assign and_ln68_2_fu_566_p2 = (or_ln68_3_fu_560_p2 & or_ln68_2_fu_542_p2);

assign and_ln68_3_fu_572_p2 = (grp_fu_1047_p_dout0 & and_ln68_2_fu_566_p2);

assign and_ln68_4_fu_654_p2 = (or_ln68_5_fu_648_p2 & or_ln68_4_fu_630_p2);

assign and_ln68_5_fu_660_p2 = (grp_fu_1051_p_dout0 & and_ln68_4_fu_654_p2);

assign and_ln68_fu_478_p2 = (or_ln68_fu_454_p2 & or_ln68_1_fu_472_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln68_1_fu_425_p1 = m_reg_819_pp0_iter6_reg;

assign bitcast_ln68_2_fu_496_p1 = m_3_reg_860_pp0_iter8_reg;

assign bitcast_ln68_3_fu_513_p1 = m_2_reg_853_pp0_iter8_reg;

assign bitcast_ln68_4_fu_584_p1 = m_5_reg_879_pp0_iter10_reg;

assign bitcast_ln68_5_fu_601_p1 = m_4_reg_872_pp0_iter10_reg;

assign bitcast_ln68_fu_408_p1 = m_1_reg_826_pp0_iter6_reg;

assign conv1_out_1_address0 = zext_ln68_2_reg_838_pp0_iter7_reg;

assign conv1_out_1_address1 = zext_ln64_6_fu_396_p1;

assign conv1_out_1_ce0 = conv1_out_1_ce0_local;

assign conv1_out_1_ce1 = conv1_out_1_ce1_local;

assign conv1_out_address0 = zext_ln68_2_fu_404_p1;

assign conv1_out_address1 = zext_ln64_6_fu_396_p1;

assign conv1_out_ce0 = conv1_out_ce0_local;

assign conv1_out_ce1 = conv1_out_ce1_local;

assign empty_fu_294_p2 = (icmp_ln61_reg_749 | and_ln60_fu_282_p2);

assign grp_fu_1043_p_ce = 1'b1;

assign grp_fu_1043_p_din0 = m_1_reg_826;

assign grp_fu_1043_p_din1 = m_reg_819;

assign grp_fu_1043_p_opcode = 5'd2;

assign grp_fu_1047_p_ce = 1'b1;

assign grp_fu_1047_p_din0 = m_3_reg_860;

assign grp_fu_1047_p_din1 = m_2_reg_853;

assign grp_fu_1047_p_opcode = 5'd2;

assign grp_fu_1051_p_ce = 1'b1;

assign grp_fu_1051_p_din0 = m_5_reg_879;

assign grp_fu_1051_p_din1 = m_4_reg_872;

assign grp_fu_1051_p_opcode = 5'd2;

assign grp_fu_676_p0 = grp_fu_676_p00;

assign grp_fu_676_p00 = select_ln60_1_reg_756;

assign grp_fu_676_p1 = 8'd13;

assign grp_fu_676_p2 = grp_fu_676_p20;

assign grp_fu_676_p20 = select_ln61_reg_768_pp0_iter2_reg;

assign grp_fu_685_p0 = grp_fu_685_p00;

assign grp_fu_685_p00 = add_ln64_fu_339_p2;

assign grp_fu_685_p1 = 12'd13;

assign grp_fu_685_p2 = zext_ln64_5_fu_390_p1;

assign grp_fu_694_p0 = grp_fu_694_p00;

assign grp_fu_694_p00 = add_ln68_fu_361_p2;

assign grp_fu_694_p1 = 12'd13;

assign grp_fu_694_p2 = zext_ln64_5_fu_390_p1;

assign grp_fu_702_p0 = grp_fu_702_p00;

assign grp_fu_702_p00 = grp_fu_676_p3;

assign grp_fu_702_p1 = 11'd13;

assign grp_fu_702_p2 = grp_fu_702_p20;

assign grp_fu_702_p20 = j_1_mid2_reg_762_pp0_iter5_reg;

assign icmp_ln60_fu_191_p2 = ((ap_sig_allocacmp_indvar_flatten22_load == 11'd1352) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_215_p2 = ((ap_sig_allocacmp_indvar_flatten9_load == 8'd169) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_276_p2 = ((j_fu_68 == 4'd13) ? 1'b1 : 1'b0);

assign icmp_ln68_10_fu_636_p2 = ((tmp_9_fu_604_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln68_11_fu_642_p2 = ((trunc_ln68_5_fu_614_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln68_1_fu_448_p2 = ((trunc_ln68_fu_421_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln68_2_fu_460_p2 = ((tmp_3_fu_428_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln68_3_fu_466_p2 = ((trunc_ln68_1_fu_438_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln68_4_fu_530_p2 = ((tmp_5_fu_499_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln68_5_fu_536_p2 = ((trunc_ln68_2_fu_509_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln68_6_fu_548_p2 = ((tmp_6_fu_516_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln68_7_fu_554_p2 = ((trunc_ln68_3_fu_526_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln68_8_fu_618_p2 = ((tmp_8_fu_587_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln68_9_fu_624_p2 = ((trunc_ln68_4_fu_597_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_442_p2 = ((tmp_2_fu_411_p4 != 8'd255) ? 1'b1 : 1'b0);

assign j_1_mid2_fu_299_p3 = ((empty_fu_294_p2[0:0] == 1'b1) ? 4'd0 : j_fu_68);

assign m_2_fu_490_p3 = ((and_ln68_1_fu_484_p2[0:0] == 1'b1) ? m_1_reg_826_pp0_iter6_reg : m_reg_819_pp0_iter6_reg);

assign m_4_fu_578_p3 = ((and_ln68_3_fu_572_p2[0:0] == 1'b1) ? m_3_reg_860_pp0_iter8_reg : m_2_reg_853_pp0_iter8_reg);

assign m_6_fu_666_p3 = ((and_ln68_5_fu_660_p2[0:0] == 1'b1) ? m_5_reg_879_pp0_iter10_reg : m_4_reg_872_pp0_iter10_reg);

assign mul_ln64_fu_321_p0 = mul_ln64_fu_321_p00;

assign mul_ln64_fu_321_p00 = select_ln60_1_reg_756;

assign mul_ln64_fu_321_p1 = 9'd26;

assign or_ln68_1_fu_472_p2 = (icmp_ln68_3_fu_466_p2 | icmp_ln68_2_fu_460_p2);

assign or_ln68_2_fu_542_p2 = (icmp_ln68_5_fu_536_p2 | icmp_ln68_4_fu_530_p2);

assign or_ln68_3_fu_560_p2 = (icmp_ln68_7_fu_554_p2 | icmp_ln68_6_fu_548_p2);

assign or_ln68_4_fu_630_p2 = (icmp_ln68_9_fu_624_p2 | icmp_ln68_8_fu_618_p2);

assign or_ln68_5_fu_648_p2 = (icmp_ln68_11_fu_642_p2 | icmp_ln68_10_fu_636_p2);

assign or_ln68_fu_454_p2 = (icmp_ln68_fu_442_p2 | icmp_ln68_1_fu_448_p2);

assign or_ln_fu_349_p3 = {{select_ln61_fu_307_p3}, {1'd1}};

assign pool1_out_address0 = zext_ln71_1_fu_672_p1;

assign pool1_out_ce0 = pool1_out_ce0_local;

assign pool1_out_d0 = m_6_reg_886;

assign pool1_out_we0 = pool1_out_we0_local;

assign select_ln60_1_fu_221_p3 = ((icmp_ln61_fu_215_p2[0:0] == 1'b1) ? add_ln60_fu_209_p2 : ap_sig_allocacmp_c_load);

assign select_ln60_fu_264_p3 = ((icmp_ln61_reg_749[0:0] == 1'b1) ? 4'd0 : i_fu_72);

assign select_ln61_1_fu_235_p3 = ((icmp_ln61_fu_215_p2[0:0] == 1'b1) ? 8'd1 : add_ln61_1_fu_229_p2);

assign select_ln61_fu_307_p3 = ((and_ln60_fu_282_p2[0:0] == 1'b1) ? add_ln61_fu_288_p2 : select_ln60_fu_264_p3);

assign shl_ln_fu_327_p3 = {{select_ln61_fu_307_p3}, {1'd0}};

assign tmp_2_fu_411_p4 = {{bitcast_ln68_fu_408_p1[30:23]}};

assign tmp_3_fu_428_p4 = {{bitcast_ln68_1_fu_425_p1[30:23]}};

assign tmp_5_fu_499_p4 = {{bitcast_ln68_2_fu_496_p1[30:23]}};

assign tmp_6_fu_516_p4 = {{bitcast_ln68_3_fu_513_p1[30:23]}};

assign tmp_8_fu_587_p4 = {{bitcast_ln68_4_fu_584_p1[30:23]}};

assign tmp_9_fu_604_p4 = {{bitcast_ln68_5_fu_601_p1[30:23]}};

assign trunc_ln68_1_fu_438_p1 = bitcast_ln68_1_fu_425_p1[22:0];

assign trunc_ln68_2_fu_509_p1 = bitcast_ln68_2_fu_496_p1[22:0];

assign trunc_ln68_3_fu_526_p1 = bitcast_ln68_3_fu_513_p1[22:0];

assign trunc_ln68_4_fu_597_p1 = bitcast_ln68_4_fu_584_p1[22:0];

assign trunc_ln68_5_fu_614_p1 = bitcast_ln68_5_fu_601_p1[22:0];

assign trunc_ln68_fu_421_p1 = bitcast_ln68_fu_408_p1[22:0];

assign xor_ln60_fu_271_p2 = (icmp_ln61_reg_749 ^ 1'd1);

assign zext_ln64_3_fu_335_p1 = shl_ln_fu_327_p3;

assign zext_ln64_5_fu_390_p1 = j_1_mid2_reg_762_pp0_iter2_reg;

assign zext_ln64_6_fu_396_p1 = grp_fu_685_p3;

assign zext_ln68_1_fu_357_p1 = or_ln_fu_349_p3;

assign zext_ln68_2_fu_404_p1 = add_ln68_1_reg_809_pp0_iter5_reg;

assign zext_ln71_1_fu_672_p1 = add_ln71_1_reg_848_pp0_iter11_reg;

always @ (posedge ap_clk) begin
    zext_ln68_2_reg_838[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln68_2_reg_838_pp0_iter7_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end

endmodule //conv2d_conv2d_Pipeline_VITIS_LOOP_60_6_VITIS_LOOP_61_7_VITIS_LOOP_62_8
