# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.srcs/sources_1/bd/system/ip/system_processing_system7_0_2/system_processing_system7_0_2.xci
# IP: The module: 'system_processing_system7_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.gen/sources_1/bd/system/ip/system_processing_system7_0_2/system_processing_system7_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_processing_system7_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.srcs/sources_1/bd/system/ip/system_processing_system7_0_2/system_processing_system7_0_2.xci
# IP: The module: 'system_processing_system7_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.gen/sources_1/bd/system/ip/system_processing_system7_0_2/system_processing_system7_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_processing_system7_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
