# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.srcs/sources_1/bd/system/ip/system_conv2d_0_10/system_conv2d_0_10.xci
# IP: The module: 'system_conv2d_0_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.gen/sources_1/bd/system/ip/system_conv2d_0_10/hdl/ip/conv2d_fadd_32ns_32ns_32_5_full_dsp_1_ip/conv2d_fadd_32ns_32ns_32_5_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv2d_fadd_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==conv2d_fadd_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.gen/sources_1/bd/system/ip/system_conv2d_0_10/hdl/ip/conv2d_fcmp_32ns_32ns_1_2_no_dsp_1_ip/conv2d_fcmp_32ns_32ns_1_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv2d_fcmp_32ns_32ns_1_2_no_dsp_1_ip || ORIG_REF_NAME==conv2d_fcmp_32ns_32ns_1_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.gen/sources_1/bd/system/ip/system_conv2d_0_10/hdl/ip/conv2d_fmul_32ns_32ns_32_4_max_dsp_1_ip/conv2d_fmul_32ns_32ns_32_4_max_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv2d_fmul_32ns_32ns_32_4_max_dsp_1_ip || ORIG_REF_NAME==conv2d_fmul_32ns_32ns_32_4_max_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.gen/sources_1/bd/system/ip/system_conv2d_0_10/constraints/conv2d_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_conv2d_0_10'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.srcs/sources_1/bd/system/ip/system_conv2d_0_10/system_conv2d_0_10.xci
# IP: The module: 'system_conv2d_0_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.gen/sources_1/bd/system/ip/system_conv2d_0_10/hdl/ip/conv2d_fadd_32ns_32ns_32_5_full_dsp_1_ip/conv2d_fadd_32ns_32ns_32_5_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv2d_fadd_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==conv2d_fadd_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.gen/sources_1/bd/system/ip/system_conv2d_0_10/hdl/ip/conv2d_fcmp_32ns_32ns_1_2_no_dsp_1_ip/conv2d_fcmp_32ns_32ns_1_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv2d_fcmp_32ns_32ns_1_2_no_dsp_1_ip || ORIG_REF_NAME==conv2d_fcmp_32ns_32ns_1_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.gen/sources_1/bd/system/ip/system_conv2d_0_10/hdl/ip/conv2d_fmul_32ns_32ns_32_4_max_dsp_1_ip/conv2d_fmul_32ns_32ns_32_4_max_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv2d_fmul_32ns_32ns_32_4_max_dsp_1_ip || ORIG_REF_NAME==conv2d_fmul_32ns_32ns_32_4_max_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/Admin/Desktop/Bharat_ARM_Challenge/zynq_cnn_basek/zynq_cnn_basek.gen/sources_1/bd/system/ip/system_conv2d_0_10/constraints/conv2d_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_conv2d_0_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
