-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_conv2d_Pipeline_VITIS_LOOP_60_6_VITIS_LOOP_61_7_VITIS_LOOP_62_8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv1_out_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_out_ce0 : OUT STD_LOGIC;
    conv1_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv1_out_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_out_ce1 : OUT STD_LOGIC;
    conv1_out_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv1_out_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_out_1_ce0 : OUT STD_LOGIC;
    conv1_out_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv1_out_1_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_out_1_ce1 : OUT STD_LOGIC;
    conv1_out_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    pool1_out_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    pool1_out_ce0 : OUT STD_LOGIC;
    pool1_out_we0 : OUT STD_LOGIC;
    pool1_out_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1043_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1043_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1043_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1043_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1043_p_ce : OUT STD_LOGIC;
    grp_fu_1047_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1047_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1047_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1047_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1047_p_ce : OUT STD_LOGIC;
    grp_fu_1051_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1051_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1051_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1051_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1051_p_ce : OUT STD_LOGIC );
end;


architecture behav of conv2d_conv2d_Pipeline_VITIS_LOOP_60_6_VITIS_LOOP_61_7_VITIS_LOOP_62_8 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_548 : STD_LOGIC_VECTOR (10 downto 0) := "10101001000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_A9 : STD_LOGIC_VECTOR (7 downto 0) := "10101001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv9_1A : STD_LOGIC_VECTOR (8 downto 0) := "000011010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv8_D : STD_LOGIC_VECTOR (7 downto 0) := "00001101";
    constant ap_const_lv12_D : STD_LOGIC_VECTOR (11 downto 0) := "000000001101";
    constant ap_const_lv11_D : STD_LOGIC_VECTOR (10 downto 0) := "00000001101";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln60_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln61_fu_215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_749 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln60_1_fu_221_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln60_1_reg_756 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_1_mid2_fu_299_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_1_mid2_reg_762 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_1_mid2_reg_762_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal j_1_mid2_reg_762_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal j_1_mid2_reg_762_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal j_1_mid2_reg_762_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln61_fu_307_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln61_reg_768 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln61_reg_768_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_5_fu_390_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_694_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln68_1_reg_809 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln68_1_reg_809_pp0_iter5_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal m_reg_819 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_reg_819_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_1_reg_826 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_1_reg_826_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln68_2_fu_404_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln68_2_reg_838 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln68_2_reg_838_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_702_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln71_1_reg_848 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln71_1_reg_848_pp0_iter8_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln71_1_reg_848_pp0_iter9_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln71_1_reg_848_pp0_iter10_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln71_1_reg_848_pp0_iter11_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal m_2_fu_490_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_2_reg_853 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_2_reg_853_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_3_reg_860 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_3_reg_860_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_4_fu_578_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_4_reg_872 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_4_reg_872_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_5_reg_879 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_5_reg_879_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_6_fu_666_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_6_reg_886 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln64_6_fu_396_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln71_1_fu_672_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_68 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln62_fu_371_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_72 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten9_fu_76 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln61_1_fu_235_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten9_load : STD_LOGIC_VECTOR (7 downto 0);
    signal c_fu_80 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten22_fu_84 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln60_1_fu_197_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten22_load : STD_LOGIC_VECTOR (10 downto 0);
    signal conv1_out_ce1_local : STD_LOGIC;
    signal conv1_out_ce0_local : STD_LOGIC;
    signal conv1_out_1_ce1_local : STD_LOGIC;
    signal conv1_out_1_ce0_local : STD_LOGIC;
    signal pool1_out_we0_local : STD_LOGIC;
    signal pool1_out_ce0_local : STD_LOGIC;
    signal add_ln60_fu_209_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln61_1_fu_229_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln62_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln60_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln60_fu_264_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln60_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln61_fu_288_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln64_fu_321_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln64_fu_321_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln_fu_327_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln64_fu_321_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln64_3_fu_335_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln64_fu_339_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_ln_fu_349_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln68_1_fu_357_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln68_fu_361_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_676_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_685_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal bitcast_ln68_fu_408_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln68_1_fu_425_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_411_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln68_fu_421_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln68_1_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln68_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_428_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln68_1_fu_438_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln68_3_fu_466_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln68_2_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_1_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln68_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln68_1_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln68_2_fu_496_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln68_3_fu_513_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_499_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln68_2_fu_509_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln68_5_fu_536_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln68_4_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_516_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln68_3_fu_526_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln68_7_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln68_6_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_2_fu_542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_3_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln68_2_fu_566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln68_3_fu_572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln68_4_fu_584_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln68_5_fu_601_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_587_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln68_4_fu_597_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln68_9_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln68_8_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_604_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln68_5_fu_614_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln68_11_fu_642_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln68_10_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_4_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_5_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln68_4_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln68_5_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_676_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_676_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_676_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_685_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_685_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_685_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_694_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_694_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_694_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_702_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_702_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_702_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_676_p00 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_676_p20 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_685_p00 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_694_p00 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_702_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_702_p20 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln64_fu_321_p00 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_mul_4ns_6ns_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component conv2d_mac_muladd_4ns_4ns_4ns_8_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component conv2d_mac_muladd_9ns_4ns_4ns_12_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component conv2d_mac_muladd_8ns_4ns_4ns_11_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component conv2d_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_4ns_6ns_9_1_1_U25 : component conv2d_mul_4ns_6ns_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 6,
        dout_WIDTH => 9)
    port map (
        din0 => mul_ln64_fu_321_p0,
        din1 => mul_ln64_fu_321_p1,
        dout => mul_ln64_fu_321_p2);

    mac_muladd_4ns_4ns_4ns_8_4_1_U26 : component conv2d_mac_muladd_4ns_4ns_4ns_8_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_676_p0,
        din1 => grp_fu_676_p1,
        din2 => grp_fu_676_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_676_p3);

    mac_muladd_9ns_4ns_4ns_12_4_1_U27 : component conv2d_mac_muladd_9ns_4ns_4ns_12_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 9,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_685_p0,
        din1 => grp_fu_685_p1,
        din2 => grp_fu_685_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_685_p3);

    mac_muladd_9ns_4ns_4ns_12_4_1_U28 : component conv2d_mac_muladd_9ns_4ns_4ns_12_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 9,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_694_p0,
        din1 => grp_fu_694_p1,
        din2 => grp_fu_694_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_694_p3);

    mac_muladd_8ns_4ns_4ns_11_4_1_U29 : component conv2d_mac_muladd_8ns_4ns_4ns_11_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 4,
        din2_WIDTH => 4,
        dout_WIDTH => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_702_p0,
        din1 => grp_fu_702_p1,
        din2 => grp_fu_702_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_702_p3);

    flow_control_loop_pipe_sequential_init_U : component conv2d_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    c_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln60_fu_191_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_80 <= select_ln60_1_fu_221_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_80 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    i_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_72 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_72 <= select_ln61_fu_307_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten22_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln60_fu_191_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten22_fu_84 <= add_ln60_1_fu_197_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten22_fu_84 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten9_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln60_fu_191_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten9_fu_76 <= select_ln61_1_fu_235_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten9_fu_76 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_68 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_68 <= add_ln62_fu_371_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                add_ln68_1_reg_809 <= grp_fu_694_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln68_1_reg_809_pp0_iter5_reg <= add_ln68_1_reg_809;
                add_ln71_1_reg_848_pp0_iter10_reg <= add_ln71_1_reg_848_pp0_iter9_reg;
                add_ln71_1_reg_848_pp0_iter11_reg <= add_ln71_1_reg_848_pp0_iter10_reg;
                add_ln71_1_reg_848_pp0_iter8_reg <= add_ln71_1_reg_848;
                add_ln71_1_reg_848_pp0_iter9_reg <= add_ln71_1_reg_848_pp0_iter8_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                j_1_mid2_reg_762_pp0_iter2_reg <= j_1_mid2_reg_762;
                j_1_mid2_reg_762_pp0_iter3_reg <= j_1_mid2_reg_762_pp0_iter2_reg;
                j_1_mid2_reg_762_pp0_iter4_reg <= j_1_mid2_reg_762_pp0_iter3_reg;
                j_1_mid2_reg_762_pp0_iter5_reg <= j_1_mid2_reg_762_pp0_iter4_reg;
                m_1_reg_826_pp0_iter6_reg <= m_1_reg_826;
                m_2_reg_853 <= m_2_fu_490_p3;
                m_2_reg_853_pp0_iter8_reg <= m_2_reg_853;
                m_3_reg_860_pp0_iter8_reg <= m_3_reg_860;
                m_4_reg_872 <= m_4_fu_578_p3;
                m_4_reg_872_pp0_iter10_reg <= m_4_reg_872;
                m_5_reg_879_pp0_iter10_reg <= m_5_reg_879;
                m_6_reg_886 <= m_6_fu_666_p3;
                m_reg_819_pp0_iter6_reg <= m_reg_819;
                select_ln61_reg_768_pp0_iter2_reg <= select_ln61_reg_768;
                    zext_ln68_2_reg_838(11 downto 0) <= zext_ln68_2_fu_404_p1(11 downto 0);
                    zext_ln68_2_reg_838_pp0_iter7_reg(11 downto 0) <= zext_ln68_2_reg_838(11 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then
                add_ln71_1_reg_848 <= grp_fu_702_p3;
                m_3_reg_860 <= conv1_out_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln61_reg_749 <= icmp_ln61_fu_215_p2;
                j_1_mid2_reg_762 <= j_1_mid2_fu_299_p3;
                select_ln60_1_reg_756 <= select_ln60_1_fu_221_p3;
                select_ln61_reg_768 <= select_ln61_fu_307_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then
                m_1_reg_826 <= conv1_out_1_q1;
                m_reg_819 <= conv1_out_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
                m_5_reg_879 <= conv1_out_1_q0;
            end if;
        end if;
    end process;
    zext_ln68_2_reg_838(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";
    zext_ln68_2_reg_838_pp0_iter7_reg(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln60_1_fu_197_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten22_load) + unsigned(ap_const_lv11_1));
    add_ln60_fu_209_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_load) + unsigned(ap_const_lv4_1));
    add_ln61_1_fu_229_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten9_load) + unsigned(ap_const_lv8_1));
    add_ln61_fu_288_p2 <= std_logic_vector(unsigned(select_ln60_fu_264_p3) + unsigned(ap_const_lv4_1));
    add_ln62_fu_371_p2 <= std_logic_vector(unsigned(j_1_mid2_fu_299_p3) + unsigned(ap_const_lv4_1));
    add_ln64_fu_339_p2 <= std_logic_vector(unsigned(mul_ln64_fu_321_p2) + unsigned(zext_ln64_3_fu_335_p1));
    add_ln68_fu_361_p2 <= std_logic_vector(unsigned(mul_ln64_fu_321_p2) + unsigned(zext_ln68_1_fu_357_p1));
    and_ln60_fu_282_p2 <= (xor_ln60_fu_271_p2 and icmp_ln62_fu_276_p2);
    and_ln68_1_fu_484_p2 <= (grp_fu_1043_p_dout0 and and_ln68_fu_478_p2);
    and_ln68_2_fu_566_p2 <= (or_ln68_3_fu_560_p2 and or_ln68_2_fu_542_p2);
    and_ln68_3_fu_572_p2 <= (grp_fu_1047_p_dout0 and and_ln68_2_fu_566_p2);
    and_ln68_4_fu_654_p2 <= (or_ln68_5_fu_648_p2 and or_ln68_4_fu_630_p2);
    and_ln68_5_fu_660_p2 <= (grp_fu_1051_p_dout0 and and_ln68_4_fu_654_p2);
    and_ln68_fu_478_p2 <= (or_ln68_fu_454_p2 and or_ln68_1_fu_472_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln60_fu_191_p2)
    begin
        if (((icmp_ln60_fu_191_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter11_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, c_fu_80)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_80;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten22_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten22_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten22_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten22_load <= indvar_flatten22_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten9_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten9_fu_76)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten9_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten9_load <= indvar_flatten9_fu_76;
        end if; 
    end process;

    bitcast_ln68_1_fu_425_p1 <= m_reg_819_pp0_iter6_reg;
    bitcast_ln68_2_fu_496_p1 <= m_3_reg_860_pp0_iter8_reg;
    bitcast_ln68_3_fu_513_p1 <= m_2_reg_853_pp0_iter8_reg;
    bitcast_ln68_4_fu_584_p1 <= m_5_reg_879_pp0_iter10_reg;
    bitcast_ln68_5_fu_601_p1 <= m_4_reg_872_pp0_iter10_reg;
    bitcast_ln68_fu_408_p1 <= m_1_reg_826_pp0_iter6_reg;
    conv1_out_1_address0 <= zext_ln68_2_reg_838_pp0_iter7_reg(12 - 1 downto 0);
    conv1_out_1_address1 <= zext_ln64_6_fu_396_p1(12 - 1 downto 0);
    conv1_out_1_ce0 <= conv1_out_1_ce0_local;

    conv1_out_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            conv1_out_1_ce0_local <= ap_const_logic_1;
        else 
            conv1_out_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv1_out_1_ce1 <= conv1_out_1_ce1_local;

    conv1_out_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            conv1_out_1_ce1_local <= ap_const_logic_1;
        else 
            conv1_out_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    conv1_out_address0 <= zext_ln68_2_fu_404_p1(12 - 1 downto 0);
    conv1_out_address1 <= zext_ln64_6_fu_396_p1(12 - 1 downto 0);
    conv1_out_ce0 <= conv1_out_ce0_local;

    conv1_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            conv1_out_ce0_local <= ap_const_logic_1;
        else 
            conv1_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv1_out_ce1 <= conv1_out_ce1_local;

    conv1_out_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            conv1_out_ce1_local <= ap_const_logic_1;
        else 
            conv1_out_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_294_p2 <= (icmp_ln61_reg_749 or and_ln60_fu_282_p2);
    grp_fu_1043_p_ce <= ap_const_logic_1;
    grp_fu_1043_p_din0 <= m_1_reg_826;
    grp_fu_1043_p_din1 <= m_reg_819;
    grp_fu_1043_p_opcode <= ap_const_lv5_2;
    grp_fu_1047_p_ce <= ap_const_logic_1;
    grp_fu_1047_p_din0 <= m_3_reg_860;
    grp_fu_1047_p_din1 <= m_2_reg_853;
    grp_fu_1047_p_opcode <= ap_const_lv5_2;
    grp_fu_1051_p_ce <= ap_const_logic_1;
    grp_fu_1051_p_din0 <= m_5_reg_879;
    grp_fu_1051_p_din1 <= m_4_reg_872;
    grp_fu_1051_p_opcode <= ap_const_lv5_2;
    grp_fu_676_p0 <= grp_fu_676_p00(4 - 1 downto 0);
    grp_fu_676_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln60_1_reg_756),8));
    grp_fu_676_p1 <= ap_const_lv8_D(4 - 1 downto 0);
    grp_fu_676_p2 <= grp_fu_676_p20(4 - 1 downto 0);
    grp_fu_676_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln61_reg_768_pp0_iter2_reg),8));
    grp_fu_685_p0 <= grp_fu_685_p00(9 - 1 downto 0);
    grp_fu_685_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_fu_339_p2),12));
    grp_fu_685_p1 <= ap_const_lv12_D(4 - 1 downto 0);
    grp_fu_685_p2 <= zext_ln64_5_fu_390_p1(4 - 1 downto 0);
    grp_fu_694_p0 <= grp_fu_694_p00(9 - 1 downto 0);
    grp_fu_694_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln68_fu_361_p2),12));
    grp_fu_694_p1 <= ap_const_lv12_D(4 - 1 downto 0);
    grp_fu_694_p2 <= zext_ln64_5_fu_390_p1(4 - 1 downto 0);
    grp_fu_702_p0 <= grp_fu_702_p00(8 - 1 downto 0);
    grp_fu_702_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_676_p3),11));
    grp_fu_702_p1 <= ap_const_lv11_D(4 - 1 downto 0);
    grp_fu_702_p2 <= grp_fu_702_p20(4 - 1 downto 0);
    grp_fu_702_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_1_mid2_reg_762_pp0_iter5_reg),11));
    icmp_ln60_fu_191_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten22_load = ap_const_lv11_548) else "0";
    icmp_ln61_fu_215_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten9_load = ap_const_lv8_A9) else "0";
    icmp_ln62_fu_276_p2 <= "1" when (j_fu_68 = ap_const_lv4_D) else "0";
    icmp_ln68_10_fu_636_p2 <= "0" when (tmp_9_fu_604_p4 = ap_const_lv8_FF) else "1";
    icmp_ln68_11_fu_642_p2 <= "1" when (trunc_ln68_5_fu_614_p1 = ap_const_lv23_0) else "0";
    icmp_ln68_1_fu_448_p2 <= "1" when (trunc_ln68_fu_421_p1 = ap_const_lv23_0) else "0";
    icmp_ln68_2_fu_460_p2 <= "0" when (tmp_3_fu_428_p4 = ap_const_lv8_FF) else "1";
    icmp_ln68_3_fu_466_p2 <= "1" when (trunc_ln68_1_fu_438_p1 = ap_const_lv23_0) else "0";
    icmp_ln68_4_fu_530_p2 <= "0" when (tmp_5_fu_499_p4 = ap_const_lv8_FF) else "1";
    icmp_ln68_5_fu_536_p2 <= "1" when (trunc_ln68_2_fu_509_p1 = ap_const_lv23_0) else "0";
    icmp_ln68_6_fu_548_p2 <= "0" when (tmp_6_fu_516_p4 = ap_const_lv8_FF) else "1";
    icmp_ln68_7_fu_554_p2 <= "1" when (trunc_ln68_3_fu_526_p1 = ap_const_lv23_0) else "0";
    icmp_ln68_8_fu_618_p2 <= "0" when (tmp_8_fu_587_p4 = ap_const_lv8_FF) else "1";
    icmp_ln68_9_fu_624_p2 <= "1" when (trunc_ln68_4_fu_597_p1 = ap_const_lv23_0) else "0";
    icmp_ln68_fu_442_p2 <= "0" when (tmp_2_fu_411_p4 = ap_const_lv8_FF) else "1";
    j_1_mid2_fu_299_p3 <= 
        ap_const_lv4_0 when (empty_fu_294_p2(0) = '1') else 
        j_fu_68;
    m_2_fu_490_p3 <= 
        m_1_reg_826_pp0_iter6_reg when (and_ln68_1_fu_484_p2(0) = '1') else 
        m_reg_819_pp0_iter6_reg;
    m_4_fu_578_p3 <= 
        m_3_reg_860_pp0_iter8_reg when (and_ln68_3_fu_572_p2(0) = '1') else 
        m_2_reg_853_pp0_iter8_reg;
    m_6_fu_666_p3 <= 
        m_5_reg_879_pp0_iter10_reg when (and_ln68_5_fu_660_p2(0) = '1') else 
        m_4_reg_872_pp0_iter10_reg;
    mul_ln64_fu_321_p0 <= mul_ln64_fu_321_p00(4 - 1 downto 0);
    mul_ln64_fu_321_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln60_1_reg_756),9));
    mul_ln64_fu_321_p1 <= ap_const_lv9_1A(6 - 1 downto 0);
    or_ln68_1_fu_472_p2 <= (icmp_ln68_3_fu_466_p2 or icmp_ln68_2_fu_460_p2);
    or_ln68_2_fu_542_p2 <= (icmp_ln68_5_fu_536_p2 or icmp_ln68_4_fu_530_p2);
    or_ln68_3_fu_560_p2 <= (icmp_ln68_7_fu_554_p2 or icmp_ln68_6_fu_548_p2);
    or_ln68_4_fu_630_p2 <= (icmp_ln68_9_fu_624_p2 or icmp_ln68_8_fu_618_p2);
    or_ln68_5_fu_648_p2 <= (icmp_ln68_11_fu_642_p2 or icmp_ln68_10_fu_636_p2);
    or_ln68_fu_454_p2 <= (icmp_ln68_fu_442_p2 or icmp_ln68_1_fu_448_p2);
    or_ln_fu_349_p3 <= (select_ln61_fu_307_p3 & ap_const_lv1_1);
    pool1_out_address0 <= zext_ln71_1_fu_672_p1(11 - 1 downto 0);
    pool1_out_ce0 <= pool1_out_ce0_local;

    pool1_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1))) then 
            pool1_out_ce0_local <= ap_const_logic_1;
        else 
            pool1_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_out_d0 <= m_6_reg_886;
    pool1_out_we0 <= pool1_out_we0_local;

    pool1_out_we0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1))) then 
            pool1_out_we0_local <= ap_const_logic_1;
        else 
            pool1_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln60_1_fu_221_p3 <= 
        add_ln60_fu_209_p2 when (icmp_ln61_fu_215_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    select_ln60_fu_264_p3 <= 
        ap_const_lv4_0 when (icmp_ln61_reg_749(0) = '1') else 
        i_fu_72;
    select_ln61_1_fu_235_p3 <= 
        ap_const_lv8_1 when (icmp_ln61_fu_215_p2(0) = '1') else 
        add_ln61_1_fu_229_p2;
    select_ln61_fu_307_p3 <= 
        add_ln61_fu_288_p2 when (and_ln60_fu_282_p2(0) = '1') else 
        select_ln60_fu_264_p3;
    shl_ln_fu_327_p3 <= (select_ln61_fu_307_p3 & ap_const_lv1_0);
    tmp_2_fu_411_p4 <= bitcast_ln68_fu_408_p1(30 downto 23);
    tmp_3_fu_428_p4 <= bitcast_ln68_1_fu_425_p1(30 downto 23);
    tmp_5_fu_499_p4 <= bitcast_ln68_2_fu_496_p1(30 downto 23);
    tmp_6_fu_516_p4 <= bitcast_ln68_3_fu_513_p1(30 downto 23);
    tmp_8_fu_587_p4 <= bitcast_ln68_4_fu_584_p1(30 downto 23);
    tmp_9_fu_604_p4 <= bitcast_ln68_5_fu_601_p1(30 downto 23);
    trunc_ln68_1_fu_438_p1 <= bitcast_ln68_1_fu_425_p1(23 - 1 downto 0);
    trunc_ln68_2_fu_509_p1 <= bitcast_ln68_2_fu_496_p1(23 - 1 downto 0);
    trunc_ln68_3_fu_526_p1 <= bitcast_ln68_3_fu_513_p1(23 - 1 downto 0);
    trunc_ln68_4_fu_597_p1 <= bitcast_ln68_4_fu_584_p1(23 - 1 downto 0);
    trunc_ln68_5_fu_614_p1 <= bitcast_ln68_5_fu_601_p1(23 - 1 downto 0);
    trunc_ln68_fu_421_p1 <= bitcast_ln68_fu_408_p1(23 - 1 downto 0);
    xor_ln60_fu_271_p2 <= (icmp_ln61_reg_749 xor ap_const_lv1_1);
    zext_ln64_3_fu_335_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_327_p3),9));
    zext_ln64_5_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_1_mid2_reg_762_pp0_iter2_reg),12));
    zext_ln64_6_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_685_p3),64));
    zext_ln68_1_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_349_p3),9));
    zext_ln68_2_fu_404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln68_1_reg_809_pp0_iter5_reg),64));
    zext_ln71_1_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln71_1_reg_848_pp0_iter11_reg),64));
end behav;
