// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module conv2d_conv2d_Pipeline_VITIS_LOOP_86_12_VITIS_LOOP_87_13_VITIS_LOOP_91_14_VITIS_LOOP_92 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sum_11,
        m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY,
        m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY,
        m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST,
        m_axi_gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID,
        m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP,
        m_axi_gmem1_0_BID,
        m_axi_gmem1_0_BUSER,
        phi_mul182,
        pool1_out_address0,
        pool1_out_ce0,
        pool1_out_q0,
        sext_ln86,
        conv2_out_address0,
        conv2_out_ce0,
        conv2_out_we0,
        conv2_out_d0,
        conv2_out_1_address0,
        conv2_out_1_ce0,
        conv2_out_1_we0,
        conv2_out_1_d0,
        grp_fu_1035_p_din0,
        grp_fu_1035_p_din1,
        grp_fu_1035_p_opcode,
        grp_fu_1035_p_dout0,
        grp_fu_1035_p_ce,
        grp_fu_1039_p_din0,
        grp_fu_1039_p_din1,
        grp_fu_1039_p_dout0,
        grp_fu_1039_p_ce,
        grp_fu_1043_p_din0,
        grp_fu_1043_p_din1,
        grp_fu_1043_p_opcode,
        grp_fu_1043_p_dout0,
        grp_fu_1043_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 6'd1;
parameter    ap_ST_fsm_pp0_stage1 = 6'd2;
parameter    ap_ST_fsm_pp0_stage2 = 6'd4;
parameter    ap_ST_fsm_pp0_stage3 = 6'd8;
parameter    ap_ST_fsm_pp0_stage4 = 6'd16;
parameter    ap_ST_fsm_pp0_stage5 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] sum_11;
output   m_axi_gmem1_0_AWVALID;
input   m_axi_gmem1_0_AWREADY;
output  [63:0] m_axi_gmem1_0_AWADDR;
output  [0:0] m_axi_gmem1_0_AWID;
output  [31:0] m_axi_gmem1_0_AWLEN;
output  [2:0] m_axi_gmem1_0_AWSIZE;
output  [1:0] m_axi_gmem1_0_AWBURST;
output  [1:0] m_axi_gmem1_0_AWLOCK;
output  [3:0] m_axi_gmem1_0_AWCACHE;
output  [2:0] m_axi_gmem1_0_AWPROT;
output  [3:0] m_axi_gmem1_0_AWQOS;
output  [3:0] m_axi_gmem1_0_AWREGION;
output  [0:0] m_axi_gmem1_0_AWUSER;
output   m_axi_gmem1_0_WVALID;
input   m_axi_gmem1_0_WREADY;
output  [31:0] m_axi_gmem1_0_WDATA;
output  [3:0] m_axi_gmem1_0_WSTRB;
output   m_axi_gmem1_0_WLAST;
output  [0:0] m_axi_gmem1_0_WID;
output  [0:0] m_axi_gmem1_0_WUSER;
output   m_axi_gmem1_0_ARVALID;
input   m_axi_gmem1_0_ARREADY;
output  [63:0] m_axi_gmem1_0_ARADDR;
output  [0:0] m_axi_gmem1_0_ARID;
output  [31:0] m_axi_gmem1_0_ARLEN;
output  [2:0] m_axi_gmem1_0_ARSIZE;
output  [1:0] m_axi_gmem1_0_ARBURST;
output  [1:0] m_axi_gmem1_0_ARLOCK;
output  [3:0] m_axi_gmem1_0_ARCACHE;
output  [2:0] m_axi_gmem1_0_ARPROT;
output  [3:0] m_axi_gmem1_0_ARQOS;
output  [3:0] m_axi_gmem1_0_ARREGION;
output  [0:0] m_axi_gmem1_0_ARUSER;
input   m_axi_gmem1_0_RVALID;
output   m_axi_gmem1_0_RREADY;
input  [31:0] m_axi_gmem1_0_RDATA;
input   m_axi_gmem1_0_RLAST;
input  [0:0] m_axi_gmem1_0_RID;
input  [8:0] m_axi_gmem1_0_RFIFONUM;
input  [0:0] m_axi_gmem1_0_RUSER;
input  [1:0] m_axi_gmem1_0_RRESP;
input   m_axi_gmem1_0_BVALID;
output   m_axi_gmem1_0_BREADY;
input  [1:0] m_axi_gmem1_0_BRESP;
input  [0:0] m_axi_gmem1_0_BID;
input  [0:0] m_axi_gmem1_0_BUSER;
input  [7:0] phi_mul182;
output  [10:0] pool1_out_address0;
output   pool1_out_ce0;
input  [31:0] pool1_out_q0;
input  [61:0] sext_ln86;
output  [10:0] conv2_out_address0;
output   conv2_out_ce0;
output   conv2_out_we0;
output  [31:0] conv2_out_d0;
output  [10:0] conv2_out_1_address0;
output   conv2_out_1_ce0;
output   conv2_out_1_we0;
output  [31:0] conv2_out_1_d0;
output  [31:0] grp_fu_1035_p_din0;
output  [31:0] grp_fu_1035_p_din1;
output  [1:0] grp_fu_1035_p_opcode;
input  [31:0] grp_fu_1035_p_dout0;
output   grp_fu_1035_p_ce;
output  [31:0] grp_fu_1039_p_din0;
output  [31:0] grp_fu_1039_p_din1;
input  [31:0] grp_fu_1039_p_dout0;
output   grp_fu_1039_p_ce;
output  [31:0] grp_fu_1043_p_din0;
output  [31:0] grp_fu_1043_p_din1;
output  [4:0] grp_fu_1043_p_opcode;
input  [0:0] grp_fu_1043_p_dout0;
output   grp_fu_1043_p_ce;

reg ap_idle;
reg m_axi_gmem1_0_ARVALID;
reg m_axi_gmem1_0_RREADY;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln86_reg_991;
reg    ap_condition_exit_pp0_iter0_stage5;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem1_blk_n_AR;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_grp1;
reg    gmem1_blk_n_R;
wire    ap_block_pp0_stage0_grp2;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
wire  signed [62:0] sext_ln86_cast_fu_252_p1;
reg  signed [62:0] sext_ln86_cast_reg_986;
wire   [0:0] icmp_ln86_fu_318_p2;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln86_reg_991_pp0_iter1_reg;
reg   [0:0] icmp_ln86_reg_991_pp0_iter2_reg;
wire   [0:0] icmp_ln87_fu_330_p2;
reg   [0:0] icmp_ln87_reg_995;
reg   [0:0] icmp_ln87_reg_995_pp0_iter1_reg;
reg   [0:0] icmp_ln87_reg_995_pp0_iter2_reg;
wire   [0:0] xor_ln86_fu_336_p2;
reg   [0:0] xor_ln86_reg_1004;
wire   [0:0] icmp_ln92_fu_342_p2;
reg   [0:0] icmp_ln92_reg_1010;
wire   [0:0] and_ln86_2_fu_354_p2;
reg   [0:0] and_ln86_2_reg_1015;
reg   [0:0] and_ln86_2_reg_1015_pp0_iter1_reg;
reg   [0:0] and_ln86_2_reg_1015_pp0_iter2_reg;
wire   [0:0] not_exitcond_flatten46_mid2105_fu_366_p2;
reg   [0:0] not_exitcond_flatten46_mid2105_reg_1023;
wire   [3:0] add_ln92_1_fu_372_p2;
reg   [3:0] add_ln92_1_reg_1029;
wire   [7:0] add_ln91_1_fu_378_p2;
reg   [7:0] add_ln91_1_reg_1034;
wire   [1:0] kj_mid2_fu_516_p3;
reg   [1:0] kj_mid2_reg_1039;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire   [5:0] add_ln92_2_fu_552_p2;
reg   [5:0] add_ln92_2_reg_1050;
wire   [3:0] zext_ln92_2_fu_558_p1;
reg   [3:0] zext_ln92_2_reg_1055;
wire   [3:0] sub_ln98_fu_570_p2;
reg   [3:0] sub_ln98_reg_1060;
wire   [0:0] icmp_ln93_1_fu_582_p2;
reg   [0:0] icmp_ln93_1_reg_1065;
reg   [0:0] icmp_ln93_1_reg_1065_pp0_iter1_reg;
reg   [0:0] icmp_ln93_1_reg_1065_pp0_iter2_reg;
reg   [0:0] icmp_ln93_1_reg_1065_pp0_iter3_reg;
wire   [0:0] icmp_ln92_1_fu_588_p2;
reg   [0:0] icmp_ln92_1_reg_1069;
reg   [0:0] icmp_ln92_1_reg_1069_pp0_iter1_reg;
reg   [0:0] icmp_ln92_1_reg_1069_pp0_iter2_reg;
reg   [0:0] icmp_ln92_1_reg_1069_pp0_iter3_reg;
wire   [0:0] icmp_ln91_1_fu_594_p2;
reg   [0:0] icmp_ln91_1_reg_1073;
reg   [0:0] icmp_ln91_1_reg_1073_pp0_iter1_reg;
reg   [0:0] icmp_ln91_1_reg_1073_pp0_iter2_reg;
reg   [0:0] icmp_ln91_1_reg_1073_pp0_iter3_reg;
reg   [63:0] gmem1_addr_reg_1077;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire   [3:0] select_ln86_2_fu_688_p3;
reg   [3:0] select_ln86_2_reg_1083;
wire    ap_block_pp0_stage4_11001_grp0;
reg    ap_block_pp0_stage4_subdone_grp0_done_reg;
wire    ap_block_pp0_stage4_subdone_grp0;
reg    ap_block_pp0_stage4_subdone;
reg   [3:0] select_ln86_2_reg_1083_pp0_iter1_reg;
reg   [3:0] select_ln86_2_reg_1083_pp0_iter2_reg;
reg   [3:0] select_ln86_2_reg_1083_pp0_iter3_reg;
wire    ap_block_pp0_stage5_11001;
wire   [3:0] select_ln86_fu_715_p3;
reg   [3:0] select_ln86_reg_1098;
wire   [0:0] trunc_ln87_fu_733_p1;
reg   [0:0] trunc_ln87_reg_1104;
reg   [0:0] trunc_ln87_reg_1104_pp0_iter2_reg;
reg   [0:0] trunc_ln87_reg_1104_pp0_iter3_reg;
reg   [2:0] lshr_ln1_reg_1113;
reg   [2:0] lshr_ln1_reg_1113_pp0_iter2_reg;
reg   [2:0] lshr_ln1_reg_1113_pp0_iter3_reg;
reg   [31:0] pool1_out_load_reg_1123;
reg   [31:0] gmem1_addr_read_reg_1128;
reg    ap_block_pp0_stage0_11001_grp2;
wire   [31:0] bitcast_ln101_fu_769_p1;
wire   [31:0] sum_19_mid257_fu_782_p3;
reg   [31:0] sum_19_mid257_reg_1138;
reg   [31:0] mul2_reg_1143;
reg   [31:0] sum_1_reg_1148;
wire   [7:0] add_ln107_fu_795_p2;
reg   [7:0] add_ln107_reg_1156;
wire   [31:0] sum_2_fu_841_p3;
reg   [31:0] sum_2_reg_1162;
wire   [63:0] zext_ln100_4_fu_765_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln107_3_fu_881_p1;
wire    ap_block_pp0_stage0_grp0;
wire  signed [63:0] sext_ln101_fu_669_p1;
wire    ap_block_pp0_stage3;
reg    ap_block_state5_io_grp1;
reg    ap_block_pp0_stage4_11001_grp1;
reg   [31:0] sum_fu_130;
reg   [31:0] ap_sig_allocacmp_sum_load;
wire    ap_block_pp0_stage4_grp0;
wire    ap_loop_init;
reg   [1:0] kj_fu_134;
wire   [1:0] add_ln93_fu_576_p2;
reg   [1:0] ki_fu_138;
wire   [1:0] select_ln92_fu_524_p3;
reg   [3:0] indvar_flatten29_fu_142;
wire   [3:0] select_ln92_1_fu_600_p3;
wire    ap_block_pp0_stage1;
reg   [3:0] ic_fu_146;
wire   [3:0] select_ln91_fu_490_p3;
reg   [7:0] indvar_flatten44_fu_150;
wire   [7:0] select_ln91_1_fu_607_p3;
reg   [3:0] j_fu_154;
wire   [3:0] select_ln87_fu_727_p3;
reg   [10:0] indvar_flatten70_fu_158;
wire   [10:0] select_ln87_1_fu_390_p3;
reg   [3:0] i_fu_162;
reg   [13:0] indvar_flatten106_fu_166;
wire   [13:0] add_ln86_1_fu_324_p2;
reg    pool1_out_ce0_local;
reg    conv2_out_we0_local;
reg    conv2_out_ce0_local;
reg    conv2_out_1_we0_local;
reg    conv2_out_1_ce0_local;
wire    ap_block_pp0_stage5;
wire   [0:0] icmp_ln91_fu_348_p2;
wire   [0:0] exitcond_flatten46_not_fu_360_p2;
wire   [10:0] add_ln87_1_fu_384_p2;
wire   [0:0] icmp_ln93_fu_417_p2;
wire   [0:0] empty_fu_428_p2;
wire   [0:0] and_ln86_fu_423_p2;
wire   [0:0] and_ln86_1_fu_445_p2;
wire   [3:0] ic_mid251_fu_432_p3;
wire   [0:0] exitcond_flatten31_mid269_fu_449_p2;
wire   [0:0] empty_29_fu_460_p2;
wire   [0:0] empty_30_fu_465_p2;
wire   [0:0] icmp_ln93_mid265_fu_440_p2;
wire   [0:0] not_exitcond_flatten31_mid269_fu_478_p2;
wire   [3:0] add_ln91_fu_454_p2;
wire   [1:0] ki_mid236_fu_470_p3;
wire   [0:0] empty_31_fu_504_p2;
wire   [0:0] icmp_ln93_mid243_fu_484_p2;
wire   [0:0] empty_32_fu_510_p2;
wire   [1:0] add_ln92_fu_498_p2;
wire   [2:0] trunc_ln92_fu_540_p1;
wire   [5:0] p_shl2_fu_544_p3;
wire   [5:0] zext_ln92_fu_536_p1;
wire   [3:0] p_shl_fu_562_p3;
wire   [6:0] zext_ln92_1_fu_639_p1;
wire   [6:0] zext_ln100_fu_642_p1;
wire   [6:0] add_ln101_1_fu_648_p2;
wire   [62:0] zext_ln93_1_fu_645_p1;
wire   [62:0] add_ln101_2_fu_658_p2;
wire   [62:0] zext_ln101_fu_654_p1;
wire   [62:0] add_ln101_fu_663_p2;
wire   [3:0] add_ln86_fu_682_p2;
wire   [3:0] add_ln100_fu_695_p2;
wire   [7:0] grp_fu_887_p3;
wire   [3:0] add_ln87_fu_722_p2;
wire   [3:0] zext_ln93_2_fu_737_p1;
wire   [3:0] add_ln100_1_fu_740_p2;
wire   [10:0] grp_fu_896_p3;
wire   [31:0] select_ln86_1_fu_776_p3;
wire   [7:0] zext_ln107_fu_792_p1;
wire   [31:0] bitcast_ln106_fu_800_p1;
wire   [7:0] tmp_s_fu_803_p4;
wire   [22:0] trunc_ln106_fu_813_p1;
wire   [0:0] icmp_ln106_1_fu_823_p2;
wire   [0:0] icmp_ln106_fu_817_p2;
wire   [0:0] or_ln106_fu_829_p2;
wire   [0:0] and_ln106_fu_835_p2;
wire   [8:0] tmp_fu_855_p3;
wire   [10:0] p_shl1_fu_848_p3;
wire   [10:0] zext_ln107_1_fu_862_p1;
wire   [10:0] sub_ln107_fu_866_p2;
wire   [10:0] zext_ln107_2_fu_872_p1;
wire   [10:0] add_ln107_1_fu_875_p2;
wire   [3:0] grp_fu_887_p0;
wire   [3:0] grp_fu_887_p1;
wire   [3:0] grp_fu_887_p2;
wire   [7:0] grp_fu_896_p0;
wire   [3:0] grp_fu_896_p1;
wire   [3:0] grp_fu_896_p2;
reg    grp_fu_239_ce;
reg    ap_block_pp0_stage0_11001;
reg    grp_fu_243_ce;
reg    ap_block_pp0_stage4_11001;
reg    grp_fu_247_ce;
wire    ap_block_pp0_stage4_00001_grp0;
reg    grp_fu_887_ce;
reg    grp_fu_896_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [5:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_block_pp0_stage5_00001;
wire   [7:0] grp_fu_887_p00;
wire   [7:0] grp_fu_887_p20;
wire   [10:0] grp_fu_896_p00;
wire   [10:0] grp_fu_896_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage4_subdone_grp0_done_reg = 1'b0;
#0 sum_fu_130 = 32'd0;
#0 kj_fu_134 = 2'd0;
#0 ki_fu_138 = 2'd0;
#0 indvar_flatten29_fu_142 = 4'd0;
#0 ic_fu_146 = 4'd0;
#0 indvar_flatten44_fu_150 = 8'd0;
#0 j_fu_154 = 4'd0;
#0 indvar_flatten70_fu_158 = 11'd0;
#0 i_fu_162 = 4'd0;
#0 indvar_flatten106_fu_166 = 14'd0;
#0 ap_done_reg = 1'b0;
end

conv2d_mac_muladd_4ns_4ns_4ns_8_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
mac_muladd_4ns_4ns_4ns_8_4_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_887_p0),
    .din1(grp_fu_887_p1),
    .din2(grp_fu_887_p2),
    .ce(grp_fu_887_ce),
    .dout(grp_fu_887_p3)
);

conv2d_mac_muladd_8ns_4ns_4ns_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 11 ))
mac_muladd_8ns_4ns_4ns_11_4_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_896_p0),
    .din1(grp_fu_896_p1),
    .din2(grp_fu_896_p2),
    .ce(grp_fu_896_ce),
    .dout(grp_fu_896_p3)
);

conv2d_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage5),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage4_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage4)) begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_block_pp0_stage4_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage4_subdone_grp0)) begin
                ap_block_pp0_stage4_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage5)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_162 <= 4'd0;
    end else if (((icmp_ln86_reg_991 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        i_fu_162 <= select_ln86_2_fu_688_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ic_fu_146 <= 4'd0;
    end else if (((icmp_ln86_reg_991 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ic_fu_146 <= select_ln91_fu_490_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten106_fu_166 <= 14'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln86_fu_318_p2 == 1'd0))) begin
        indvar_flatten106_fu_166 <= add_ln86_1_fu_324_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten29_fu_142 <= 4'd0;
    end else if (((icmp_ln86_reg_991 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten29_fu_142 <= select_ln92_1_fu_600_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten44_fu_150 <= 8'd0;
    end else if (((icmp_ln86_reg_991 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten44_fu_150 <= select_ln91_1_fu_607_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten70_fu_158 <= 11'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln86_fu_318_p2 == 1'd0))) begin
        indvar_flatten70_fu_158 <= select_ln87_1_fu_390_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_154 <= 4'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        j_fu_154 <= select_ln87_fu_727_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ki_fu_138 <= 2'd0;
    end else if (((icmp_ln86_reg_991 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ki_fu_138 <= select_ln92_fu_524_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kj_fu_134 <= 2'd0;
    end else if (((icmp_ln86_reg_991 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        kj_fu_134 <= add_ln93_fu_576_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_fu_130 <= sum_11;
    end else if (((1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        sum_fu_130 <= sum_1_reg_1148;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln107_reg_1156 <= add_ln107_fu_795_p2;
        sum_2_reg_1162 <= sum_2_fu_841_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln91_1_reg_1034 <= add_ln91_1_fu_378_p2;
        add_ln92_1_reg_1029 <= add_ln92_1_fu_372_p2;
        and_ln86_2_reg_1015 <= and_ln86_2_fu_354_p2;
        and_ln86_2_reg_1015_pp0_iter1_reg <= and_ln86_2_reg_1015;
        and_ln86_2_reg_1015_pp0_iter2_reg <= and_ln86_2_reg_1015_pp0_iter1_reg;
        icmp_ln86_reg_991 <= icmp_ln86_fu_318_p2;
        icmp_ln86_reg_991_pp0_iter1_reg <= icmp_ln86_reg_991;
        icmp_ln86_reg_991_pp0_iter2_reg <= icmp_ln86_reg_991_pp0_iter1_reg;
        icmp_ln87_reg_995 <= icmp_ln87_fu_330_p2;
        icmp_ln87_reg_995_pp0_iter1_reg <= icmp_ln87_reg_995;
        icmp_ln87_reg_995_pp0_iter2_reg <= icmp_ln87_reg_995_pp0_iter1_reg;
        icmp_ln92_reg_1010 <= icmp_ln92_fu_342_p2;
        lshr_ln1_reg_1113 <= {{select_ln87_fu_727_p3[3:1]}};
        lshr_ln1_reg_1113_pp0_iter2_reg <= lshr_ln1_reg_1113;
        lshr_ln1_reg_1113_pp0_iter3_reg <= lshr_ln1_reg_1113_pp0_iter2_reg;
        not_exitcond_flatten46_mid2105_reg_1023 <= not_exitcond_flatten46_mid2105_fu_366_p2;
        trunc_ln87_reg_1104 <= trunc_ln87_fu_733_p1;
        trunc_ln87_reg_1104_pp0_iter2_reg <= trunc_ln87_reg_1104;
        trunc_ln87_reg_1104_pp0_iter3_reg <= trunc_ln87_reg_1104_pp0_iter2_reg;
        xor_ln86_reg_1004 <= xor_ln86_fu_336_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln92_2_reg_1050 <= add_ln92_2_fu_552_p2;
        icmp_ln91_1_reg_1073 <= icmp_ln91_1_fu_594_p2;
        icmp_ln91_1_reg_1073_pp0_iter1_reg <= icmp_ln91_1_reg_1073;
        icmp_ln91_1_reg_1073_pp0_iter2_reg <= icmp_ln91_1_reg_1073_pp0_iter1_reg;
        icmp_ln91_1_reg_1073_pp0_iter3_reg <= icmp_ln91_1_reg_1073_pp0_iter2_reg;
        icmp_ln92_1_reg_1069 <= icmp_ln92_1_fu_588_p2;
        icmp_ln92_1_reg_1069_pp0_iter1_reg <= icmp_ln92_1_reg_1069;
        icmp_ln92_1_reg_1069_pp0_iter2_reg <= icmp_ln92_1_reg_1069_pp0_iter1_reg;
        icmp_ln92_1_reg_1069_pp0_iter3_reg <= icmp_ln92_1_reg_1069_pp0_iter2_reg;
        icmp_ln93_1_reg_1065 <= icmp_ln93_1_fu_582_p2;
        icmp_ln93_1_reg_1065_pp0_iter1_reg <= icmp_ln93_1_reg_1065;
        icmp_ln93_1_reg_1065_pp0_iter2_reg <= icmp_ln93_1_reg_1065_pp0_iter1_reg;
        icmp_ln93_1_reg_1065_pp0_iter3_reg <= icmp_ln93_1_reg_1065_pp0_iter2_reg;
        kj_mid2_reg_1039 <= kj_mid2_fu_516_p3;
        sub_ln98_reg_1060 <= sub_ln98_fu_570_p2;
        zext_ln92_2_reg_1055[1 : 0] <= zext_ln92_2_fu_558_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem1_addr_read_reg_1128 <= m_axi_gmem1_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        gmem1_addr_reg_1077 <= sext_ln101_fu_669_p1;
        pool1_out_load_reg_1123 <= pool1_out_q0;
        sum_1_reg_1148 <= grp_fu_1035_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        mul2_reg_1143 <= grp_fu_1039_p_dout0;
        select_ln86_2_reg_1083 <= select_ln86_2_fu_688_p3;
        select_ln86_2_reg_1083_pp0_iter1_reg <= select_ln86_2_reg_1083;
        select_ln86_2_reg_1083_pp0_iter2_reg <= select_ln86_2_reg_1083_pp0_iter1_reg;
        select_ln86_2_reg_1083_pp0_iter3_reg <= select_ln86_2_reg_1083_pp0_iter2_reg;
        sum_19_mid257_reg_1138 <= sum_19_mid257_fu_782_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln86_reg_1098 <= select_ln86_fu_715_p3;
        sext_ln86_cast_reg_986 <= sext_ln86_cast_fu_252_p1;
    end
end

always @ (*) begin
    if (((icmp_ln86_reg_991 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_condition_exit_pp0_iter0_stage5 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln86_reg_991_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_sig_allocacmp_sum_load = sum_1_reg_1148;
    end else begin
        ap_sig_allocacmp_sum_load = sum_fu_130;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv2_out_1_ce0_local = 1'b1;
    end else begin
        conv2_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln87_reg_1104_pp0_iter3_reg == 1'd1) & (icmp_ln91_1_reg_1073_pp0_iter3_reg == 1'd1) & (icmp_ln92_1_reg_1069_pp0_iter3_reg == 1'd1) & (icmp_ln93_1_reg_1065_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv2_out_1_we0_local = 1'b1;
    end else begin
        conv2_out_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv2_out_ce0_local = 1'b1;
    end else begin
        conv2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln87_reg_1104_pp0_iter3_reg == 1'd0) & (icmp_ln91_1_reg_1073_pp0_iter3_reg == 1'd1) & (icmp_ln92_1_reg_1069_pp0_iter3_reg == 1'd1) & (icmp_ln93_1_reg_1065_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv2_out_we0_local = 1'b1;
    end else begin
        conv2_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln86_reg_991 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_grp1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        gmem1_blk_n_AR = m_axi_gmem1_0_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem1_blk_n_R = m_axi_gmem1_0_RVALID;
    end else begin
        gmem1_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_239_ce = 1'b1;
    end else begin
        grp_fu_239_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_243_ce = 1'b1;
    end else begin
        grp_fu_243_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        grp_fu_247_ce = 1'b1;
    end else begin
        grp_fu_247_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_887_ce = 1'b1;
    end else begin
        grp_fu_887_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_896_ce = 1'b1;
    end else begin
        grp_fu_896_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln86_reg_991 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        m_axi_gmem1_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem1_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem1_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem1_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        pool1_out_ce0_local = 1'b1;
    end else begin
        pool1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln100_1_fu_740_p2 = (zext_ln93_2_fu_737_p1 + select_ln87_fu_727_p3);

assign add_ln100_fu_695_p2 = (zext_ln92_2_reg_1055 + select_ln86_2_fu_688_p3);

assign add_ln101_1_fu_648_p2 = (zext_ln92_1_fu_639_p1 + zext_ln100_fu_642_p1);

assign add_ln101_2_fu_658_p2 = ($signed(zext_ln93_1_fu_645_p1) + $signed(sext_ln86_cast_reg_986));

assign add_ln101_fu_663_p2 = (add_ln101_2_fu_658_p2 + zext_ln101_fu_654_p1);

assign add_ln107_1_fu_875_p2 = (sub_ln107_fu_866_p2 + zext_ln107_2_fu_872_p1);

assign add_ln107_fu_795_p2 = (phi_mul182 + zext_ln107_fu_792_p1);

assign add_ln86_1_fu_324_p2 = (indvar_flatten106_fu_166 + 14'd1);

assign add_ln86_fu_682_p2 = (i_fu_162 + 4'd1);

assign add_ln87_1_fu_384_p2 = (indvar_flatten70_fu_158 + 11'd1);

assign add_ln87_fu_722_p2 = (select_ln86_reg_1098 + 4'd1);

assign add_ln91_1_fu_378_p2 = (indvar_flatten44_fu_150 + 8'd1);

assign add_ln91_fu_454_p2 = (ic_mid251_fu_432_p3 + 4'd1);

assign add_ln92_1_fu_372_p2 = (indvar_flatten29_fu_142 + 4'd1);

assign add_ln92_2_fu_552_p2 = (p_shl2_fu_544_p3 + zext_ln92_fu_536_p1);

assign add_ln92_fu_498_p2 = (ki_mid236_fu_470_p3 + 2'd1);

assign add_ln93_fu_576_p2 = (kj_mid2_fu_516_p3 + 2'd1);

assign and_ln106_fu_835_p2 = (or_ln106_fu_829_p2 & grp_fu_1043_p_dout0);

assign and_ln86_1_fu_445_p2 = (xor_ln86_reg_1004 & icmp_ln92_reg_1010);

assign and_ln86_2_fu_354_p2 = (xor_ln86_fu_336_p2 & icmp_ln91_fu_348_p2);

assign and_ln86_fu_423_p2 = (xor_ln86_reg_1004 & icmp_ln93_fu_417_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_0_RVALID == 1'b0));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_0_RVALID == 1'b0));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (m_axi_gmem1_0_RVALID == 1'b0));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_00001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_io_grp1));
end

assign ap_block_pp0_stage4_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_io_grp1));
end

assign ap_block_pp0_stage4_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state5_io_grp1));
end

assign ap_block_pp0_stage4_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io_grp1 = ((m_axi_gmem1_0_ARREADY == 1'b0) & (icmp_ln86_reg_991 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage5;

assign ap_ready = ap_ready_sig;

assign bitcast_ln101_fu_769_p1 = gmem1_addr_read_reg_1128;

assign bitcast_ln106_fu_800_p1 = sum_1_reg_1148;

assign conv2_out_1_address0 = zext_ln107_3_fu_881_p1;

assign conv2_out_1_ce0 = conv2_out_1_ce0_local;

assign conv2_out_1_d0 = sum_2_reg_1162;

assign conv2_out_1_we0 = conv2_out_1_we0_local;

assign conv2_out_address0 = zext_ln107_3_fu_881_p1;

assign conv2_out_ce0 = conv2_out_ce0_local;

assign conv2_out_d0 = sum_2_reg_1162;

assign conv2_out_we0 = conv2_out_we0_local;

assign empty_29_fu_460_p2 = (exitcond_flatten31_mid269_fu_449_p2 | and_ln86_2_reg_1015);

assign empty_30_fu_465_p2 = (icmp_ln87_reg_995 | empty_29_fu_460_p2);

assign empty_31_fu_504_p2 = (exitcond_flatten31_mid269_fu_449_p2 | empty_fu_428_p2);

assign empty_32_fu_510_p2 = (icmp_ln93_mid243_fu_484_p2 | empty_31_fu_504_p2);

assign empty_fu_428_p2 = (icmp_ln87_reg_995 | and_ln86_2_reg_1015);

assign exitcond_flatten31_mid269_fu_449_p2 = (not_exitcond_flatten46_mid2105_reg_1023 & and_ln86_1_fu_445_p2);

assign exitcond_flatten46_not_fu_360_p2 = (icmp_ln91_fu_348_p2 ^ 1'd1);

assign grp_fu_1035_p_ce = grp_fu_239_ce;

assign grp_fu_1035_p_din0 = sum_19_mid257_reg_1138;

assign grp_fu_1035_p_din1 = mul2_reg_1143;

assign grp_fu_1035_p_opcode = 2'd0;

assign grp_fu_1039_p_ce = grp_fu_243_ce;

assign grp_fu_1039_p_din0 = pool1_out_load_reg_1123;

assign grp_fu_1039_p_din1 = bitcast_ln101_fu_769_p1;

assign grp_fu_1043_p_ce = grp_fu_247_ce;

assign grp_fu_1043_p_din0 = sum_1_reg_1148;

assign grp_fu_1043_p_din1 = 32'd0;

assign grp_fu_1043_p_opcode = 5'd4;

assign grp_fu_887_p0 = grp_fu_887_p00;

assign grp_fu_887_p00 = select_ln91_fu_490_p3;

assign grp_fu_887_p1 = 8'd13;

assign grp_fu_887_p2 = grp_fu_887_p20;

assign grp_fu_887_p20 = add_ln100_fu_695_p2;

assign grp_fu_896_p0 = grp_fu_896_p00;

assign grp_fu_896_p00 = grp_fu_887_p3;

assign grp_fu_896_p1 = 11'd13;

assign grp_fu_896_p2 = grp_fu_896_p20;

assign grp_fu_896_p20 = add_ln100_1_fu_740_p2;

assign ic_mid251_fu_432_p3 = ((empty_fu_428_p2[0:0] == 1'b1) ? 4'd0 : ic_fu_146);

assign icmp_ln106_1_fu_823_p2 = ((trunc_ln106_fu_813_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln106_fu_817_p2 = ((tmp_s_fu_803_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_318_p2 = ((indvar_flatten106_fu_166 == 14'd8712) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_330_p2 = ((indvar_flatten70_fu_158 == 11'd792) ? 1'b1 : 1'b0);

assign icmp_ln91_1_fu_594_p2 = ((select_ln91_fu_490_p3 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_348_p2 = ((indvar_flatten44_fu_150 == 8'd72) ? 1'b1 : 1'b0);

assign icmp_ln92_1_fu_588_p2 = ((select_ln92_fu_524_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_342_p2 = ((indvar_flatten29_fu_142 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln93_1_fu_582_p2 = ((add_ln93_fu_576_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_417_p2 = ((kj_fu_134 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln93_mid243_fu_484_p2 = (not_exitcond_flatten31_mid269_fu_478_p2 & icmp_ln93_mid265_fu_440_p2);

assign icmp_ln93_mid265_fu_440_p2 = (not_exitcond_flatten46_mid2105_reg_1023 & and_ln86_fu_423_p2);

assign ki_mid236_fu_470_p3 = ((empty_30_fu_465_p2[0:0] == 1'b1) ? 2'd0 : ki_fu_138);

assign kj_mid2_fu_516_p3 = ((empty_32_fu_510_p2[0:0] == 1'b1) ? 2'd0 : kj_fu_134);

assign m_axi_gmem1_0_ARADDR = gmem1_addr_reg_1077;

assign m_axi_gmem1_0_ARBURST = 2'd0;

assign m_axi_gmem1_0_ARCACHE = 4'd0;

assign m_axi_gmem1_0_ARID = 1'd0;

assign m_axi_gmem1_0_ARLEN = 64'd1;

assign m_axi_gmem1_0_ARLOCK = 2'd0;

assign m_axi_gmem1_0_ARPROT = 3'd0;

assign m_axi_gmem1_0_ARQOS = 4'd0;

assign m_axi_gmem1_0_ARREGION = 4'd0;

assign m_axi_gmem1_0_ARSIZE = 3'd0;

assign m_axi_gmem1_0_ARUSER = 1'd0;

assign m_axi_gmem1_0_AWADDR = 64'd0;

assign m_axi_gmem1_0_AWBURST = 2'd0;

assign m_axi_gmem1_0_AWCACHE = 4'd0;

assign m_axi_gmem1_0_AWID = 1'd0;

assign m_axi_gmem1_0_AWLEN = 32'd0;

assign m_axi_gmem1_0_AWLOCK = 2'd0;

assign m_axi_gmem1_0_AWPROT = 3'd0;

assign m_axi_gmem1_0_AWQOS = 4'd0;

assign m_axi_gmem1_0_AWREGION = 4'd0;

assign m_axi_gmem1_0_AWSIZE = 3'd0;

assign m_axi_gmem1_0_AWUSER = 1'd0;

assign m_axi_gmem1_0_AWVALID = 1'b0;

assign m_axi_gmem1_0_BREADY = 1'b0;

assign m_axi_gmem1_0_WDATA = 32'd0;

assign m_axi_gmem1_0_WID = 1'd0;

assign m_axi_gmem1_0_WLAST = 1'b0;

assign m_axi_gmem1_0_WSTRB = 4'd0;

assign m_axi_gmem1_0_WUSER = 1'd0;

assign m_axi_gmem1_0_WVALID = 1'b0;

assign not_exitcond_flatten31_mid269_fu_478_p2 = (exitcond_flatten31_mid269_fu_449_p2 ^ 1'd1);

assign not_exitcond_flatten46_mid2105_fu_366_p2 = (icmp_ln87_fu_330_p2 | exitcond_flatten46_not_fu_360_p2);

assign or_ln106_fu_829_p2 = (icmp_ln106_fu_817_p2 | icmp_ln106_1_fu_823_p2);

assign p_shl1_fu_848_p3 = {{add_ln107_reg_1156}, {3'd0}};

assign p_shl2_fu_544_p3 = {{trunc_ln92_fu_540_p1}, {3'd0}};

assign p_shl_fu_562_p3 = {{select_ln92_fu_524_p3}, {2'd0}};

assign pool1_out_address0 = zext_ln100_4_fu_765_p1;

assign pool1_out_ce0 = pool1_out_ce0_local;

assign select_ln86_1_fu_776_p3 = ((icmp_ln87_reg_995_pp0_iter2_reg[0:0] == 1'b1) ? sum_11 : ap_sig_allocacmp_sum_load);

assign select_ln86_2_fu_688_p3 = ((icmp_ln87_reg_995[0:0] == 1'b1) ? add_ln86_fu_682_p2 : i_fu_162);

assign select_ln86_fu_715_p3 = ((icmp_ln87_reg_995[0:0] == 1'b1) ? 4'd0 : j_fu_154);

assign select_ln87_1_fu_390_p3 = ((icmp_ln87_fu_330_p2[0:0] == 1'b1) ? 11'd1 : add_ln87_1_fu_384_p2);

assign select_ln87_fu_727_p3 = ((and_ln86_2_reg_1015[0:0] == 1'b1) ? add_ln87_fu_722_p2 : select_ln86_reg_1098);

assign select_ln91_1_fu_607_p3 = ((empty_fu_428_p2[0:0] == 1'b1) ? 8'd1 : add_ln91_1_reg_1034);

assign select_ln91_fu_490_p3 = ((exitcond_flatten31_mid269_fu_449_p2[0:0] == 1'b1) ? add_ln91_fu_454_p2 : ic_mid251_fu_432_p3);

assign select_ln92_1_fu_600_p3 = ((empty_30_fu_465_p2[0:0] == 1'b1) ? 4'd1 : add_ln92_1_reg_1029);

assign select_ln92_fu_524_p3 = ((icmp_ln93_mid243_fu_484_p2[0:0] == 1'b1) ? add_ln92_fu_498_p2 : ki_mid236_fu_470_p3);

assign sext_ln101_fu_669_p1 = $signed(add_ln101_fu_663_p2);

assign sext_ln86_cast_fu_252_p1 = $signed(sext_ln86);

assign sub_ln107_fu_866_p2 = (p_shl1_fu_848_p3 - zext_ln107_1_fu_862_p1);

assign sub_ln98_fu_570_p2 = (p_shl_fu_562_p3 - zext_ln92_2_fu_558_p1);

assign sum_19_mid257_fu_782_p3 = ((and_ln86_2_reg_1015_pp0_iter2_reg[0:0] == 1'b1) ? sum_11 : select_ln86_1_fu_776_p3);

assign sum_2_fu_841_p3 = ((and_ln106_fu_835_p2[0:0] == 1'b1) ? 32'd0 : sum_1_reg_1148);

assign tmp_fu_855_p3 = {{add_ln107_reg_1156}, {1'd0}};

assign tmp_s_fu_803_p4 = {{bitcast_ln106_fu_800_p1[30:23]}};

assign trunc_ln106_fu_813_p1 = bitcast_ln106_fu_800_p1[22:0];

assign trunc_ln87_fu_733_p1 = select_ln87_fu_727_p3[0:0];

assign trunc_ln92_fu_540_p1 = select_ln91_fu_490_p3[2:0];

assign xor_ln86_fu_336_p2 = (icmp_ln87_fu_330_p2 ^ 1'd1);

assign zext_ln100_4_fu_765_p1 = grp_fu_896_p3;

assign zext_ln100_fu_642_p1 = sub_ln98_reg_1060;

assign zext_ln101_fu_654_p1 = add_ln101_1_fu_648_p2;

assign zext_ln107_1_fu_862_p1 = tmp_fu_855_p3;

assign zext_ln107_2_fu_872_p1 = lshr_ln1_reg_1113_pp0_iter3_reg;

assign zext_ln107_3_fu_881_p1 = add_ln107_1_fu_875_p2;

assign zext_ln107_fu_792_p1 = select_ln86_2_reg_1083_pp0_iter3_reg;

assign zext_ln92_1_fu_639_p1 = add_ln92_2_reg_1050;

assign zext_ln92_2_fu_558_p1 = select_ln92_fu_524_p3;

assign zext_ln92_fu_536_p1 = select_ln91_fu_490_p3;

assign zext_ln93_1_fu_645_p1 = kj_mid2_reg_1039;

assign zext_ln93_2_fu_737_p1 = kj_mid2_reg_1039;

always @ (posedge ap_clk) begin
    zext_ln92_2_reg_1055[3:2] <= 2'b00;
end

endmodule //conv2d_conv2d_Pipeline_VITIS_LOOP_86_12_VITIS_LOOP_87_13_VITIS_LOOP_91_14_VITIS_LOOP_92
