-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_conv2d_Pipeline_VITIS_LOOP_116_17_VITIS_LOOP_117_18_VITIS_LOOP_118_19 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv2_out_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_out_ce0 : OUT STD_LOGIC;
    conv2_out_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv2_out_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_out_ce1 : OUT STD_LOGIC;
    conv2_out_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv2_out_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_out_1_ce0 : OUT STD_LOGIC;
    conv2_out_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv2_out_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_out_1_ce1 : OUT STD_LOGIC;
    conv2_out_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    pool2_out_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    pool2_out_ce0 : OUT STD_LOGIC;
    pool2_out_we0 : OUT STD_LOGIC;
    pool2_out_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1043_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1043_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1043_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1043_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1043_p_ce : OUT STD_LOGIC;
    grp_fu_1047_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1047_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1047_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1047_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1047_p_ce : OUT STD_LOGIC;
    grp_fu_1051_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1051_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1051_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_1051_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_1051_p_ce : OUT STD_LOGIC );
end;


architecture behav of conv2d_conv2d_Pipeline_VITIS_LOOP_116_17_VITIS_LOOP_117_18_VITIS_LOOP_118_19 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_190 : STD_LOGIC_VECTOR (8 downto 0) := "110010000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv9_B : STD_LOGIC_VECTOR (8 downto 0) := "000001011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln116_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln117_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_reg_830 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln116_1_fu_229_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln116_1_reg_837 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln116_1_reg_837_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal j_3_mid2_fu_307_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_3_mid2_reg_844 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_3_mid2_reg_844_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln117_fu_315_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln117_reg_850 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln120_fu_326_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln120_reg_856 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln120_fu_344_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln120_reg_861 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln120_fu_350_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_reg_866 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln127_fu_393_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln127_reg_871 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln127_fu_399_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln127_reg_876 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln124_1_fu_488_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln124_1_reg_886 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln124_1_reg_886_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln127_1_fu_513_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln127_1_reg_896 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln127_1_reg_896_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln127_1_reg_896_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln127_1_reg_896_pp0_iter6_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln127_1_reg_896_pp0_iter7_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln127_1_reg_896_pp0_iter8_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln127_1_reg_896_pp0_iter9_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal m_reg_901 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_reg_901_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_7_reg_908 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_7_reg_908_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln124_2_fu_519_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln124_2_reg_915 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln124_2_reg_915_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal m_8_fu_605_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_8_reg_925 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_8_reg_925_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_9_reg_932 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_9_reg_932_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_10_fu_693_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_10_reg_944 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_10_reg_944_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_11_reg_951 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_11_reg_951_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal m_12_fu_781_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_12_reg_958 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln120_7_fu_482_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln127_2_fu_787_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_76 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln118_fu_354_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_80 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal indvar_flatten113_fu_84 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln117_1_fu_243_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten113_load : STD_LOGIC_VECTOR (5 downto 0);
    signal c_fu_88 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten126_fu_92 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln116_1_fu_205_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_indvar_flatten126_load : STD_LOGIC_VECTOR (8 downto 0);
    signal conv2_out_ce1_local : STD_LOGIC;
    signal conv2_out_ce0_local : STD_LOGIC;
    signal conv2_out_1_ce1_local : STD_LOGIC;
    signal conv2_out_1_ce0_local : STD_LOGIC;
    signal pool2_out_we0_local : STD_LOGIC;
    signal pool2_out_ce0_local : STD_LOGIC;
    signal add_ln116_fu_217_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln117_1_fu_237_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln118_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln116_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln116_fu_272_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln116_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln117_fu_296_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln120_fu_326_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln120_fu_326_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln2_fu_332_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln120_3_fu_340_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_373_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln127_fu_380_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln120_fu_370_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln127_2_fu_384_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln127_1_fu_390_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_403_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_fu_410_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln120_4_fu_417_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_ln1_fu_427_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln124_fu_434_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln124_fu_438_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln124_fu_443_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_447_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_6_fu_455_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln124_1_fu_463_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln124_fu_421_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln120_6_fu_473_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln120_1_fu_476_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln118_fu_467_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl_fu_497_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln120_2_fu_494_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln120_2_fu_504_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln120_5_fu_510_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal bitcast_ln124_fu_523_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln124_1_fu_540_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_526_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln124_1_fu_536_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln124_1_fu_563_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_543_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln124_2_fu_553_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln124_3_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_2_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln124_fu_569_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln124_1_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln124_fu_593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln124_1_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln124_2_fu_611_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln124_3_fu_628_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_614_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln124_3_fu_624_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln124_5_fu_651_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_4_fu_645_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_631_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln124_4_fu_641_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln124_7_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_6_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln124_2_fu_657_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln124_3_fu_675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln124_2_fu_681_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln124_3_fu_687_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln124_4_fu_699_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln124_5_fu_716_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_702_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln124_5_fu_712_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln124_9_fu_739_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_8_fu_733_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_719_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln124_6_fu_729_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln124_11_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln124_10_fu_751_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln124_4_fu_745_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln124_5_fu_763_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln124_4_fu_769_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln124_5_fu_775_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln120_fu_326_p00 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_mul_5ns_5ns_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component conv2d_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_5ns_5ns_9_1_1_U52 : component conv2d_mul_5ns_5ns_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        dout_WIDTH => 9)
    port map (
        din0 => mul_ln120_fu_326_p0,
        din1 => mul_ln120_fu_326_p1,
        dout => mul_ln120_fu_326_p2);

    flow_control_loop_pipe_sequential_init_U : component conv2d_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    c_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln116_fu_199_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_88 <= select_ln116_1_fu_229_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_88 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    i_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_80 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_80 <= select_ln117_fu_315_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten113_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln116_fu_199_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten113_fu_84 <= select_ln117_1_fu_243_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten113_fu_84 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten126_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln116_fu_199_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten126_fu_92 <= add_ln116_1_fu_205_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten126_fu_92 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_76 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_76 <= add_ln118_fu_354_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln120_reg_861 <= add_ln120_fu_344_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln117_reg_830 <= icmp_ln117_fu_223_p2;
                j_3_mid2_reg_844 <= j_3_mid2_fu_307_p3;
                mul_ln120_reg_856 <= mul_ln120_fu_326_p2;
                select_ln116_1_reg_837 <= select_ln116_1_fu_229_p3;
                select_ln116_1_reg_837_pp0_iter1_reg <= select_ln116_1_reg_837;
                select_ln117_reg_850 <= select_ln117_fu_315_p3;
                trunc_ln120_reg_866 <= trunc_ln120_fu_350_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln124_1_reg_886 <= add_ln124_1_fu_488_p2;
                add_ln124_1_reg_886_pp0_iter3_reg <= add_ln124_1_reg_886;
                add_ln127_1_reg_896 <= add_ln127_1_fu_513_p2;
                add_ln127_1_reg_896_pp0_iter4_reg <= add_ln127_1_reg_896;
                add_ln127_1_reg_896_pp0_iter5_reg <= add_ln127_1_reg_896_pp0_iter4_reg;
                add_ln127_1_reg_896_pp0_iter6_reg <= add_ln127_1_reg_896_pp0_iter5_reg;
                add_ln127_1_reg_896_pp0_iter7_reg <= add_ln127_1_reg_896_pp0_iter6_reg;
                add_ln127_1_reg_896_pp0_iter8_reg <= add_ln127_1_reg_896_pp0_iter7_reg;
                add_ln127_1_reg_896_pp0_iter9_reg <= add_ln127_1_reg_896_pp0_iter8_reg;
                add_ln127_reg_871 <= add_ln127_fu_393_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                j_3_mid2_reg_844_pp0_iter2_reg <= j_3_mid2_reg_844;
                m_10_reg_944 <= m_10_fu_693_p3;
                m_10_reg_944_pp0_iter8_reg <= m_10_reg_944;
                m_11_reg_951_pp0_iter8_reg <= m_11_reg_951;
                m_12_reg_958 <= m_12_fu_781_p3;
                m_7_reg_908_pp0_iter4_reg <= m_7_reg_908;
                m_8_reg_925 <= m_8_fu_605_p3;
                m_8_reg_925_pp0_iter6_reg <= m_8_reg_925;
                m_9_reg_932_pp0_iter6_reg <= m_9_reg_932;
                m_reg_901_pp0_iter4_reg <= m_reg_901;
                trunc_ln127_reg_876 <= trunc_ln127_fu_399_p1;
                    zext_ln124_2_reg_915(10 downto 0) <= zext_ln124_2_fu_519_p1(10 downto 0);
                    zext_ln124_2_reg_915_pp0_iter5_reg(10 downto 0) <= zext_ln124_2_reg_915(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then
                m_11_reg_951 <= conv2_out_1_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                m_7_reg_908 <= conv2_out_1_q1;
                m_reg_901 <= conv2_out_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then
                m_9_reg_932 <= conv2_out_q0;
            end if;
        end if;
    end process;
    zext_ln124_2_reg_915(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln124_2_reg_915_pp0_iter5_reg(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln116_1_fu_205_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten126_load) + unsigned(ap_const_lv9_1));
    add_ln116_fu_217_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_load) + unsigned(ap_const_lv5_1));
    add_ln117_1_fu_237_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten113_load) + unsigned(ap_const_lv6_1));
    add_ln117_fu_296_p2 <= std_logic_vector(unsigned(select_ln116_fu_272_p3) + unsigned(ap_const_lv3_1));
    add_ln118_fu_354_p2 <= std_logic_vector(unsigned(j_3_mid2_fu_307_p3) + unsigned(ap_const_lv3_1));
    add_ln120_1_fu_476_p2 <= std_logic_vector(unsigned(sub_ln124_fu_421_p2) + unsigned(zext_ln120_6_fu_473_p1));
    add_ln120_2_fu_504_p2 <= std_logic_vector(unsigned(p_shl_fu_497_p3) + unsigned(zext_ln120_2_fu_494_p1));
    add_ln120_fu_344_p2 <= std_logic_vector(unsigned(mul_ln120_fu_326_p2) + unsigned(zext_ln120_3_fu_340_p1));
    add_ln124_1_fu_488_p2 <= std_logic_vector(unsigned(sub_ln118_fu_467_p2) + unsigned(zext_ln120_6_fu_473_p1));
    add_ln124_fu_438_p2 <= std_logic_vector(unsigned(mul_ln120_reg_856) + unsigned(zext_ln124_fu_434_p1));
    add_ln127_1_fu_513_p2 <= std_logic_vector(unsigned(add_ln120_2_fu_504_p2) + unsigned(zext_ln120_5_fu_510_p1));
    add_ln127_2_fu_384_p2 <= std_logic_vector(unsigned(zext_ln127_fu_380_p1) + unsigned(zext_ln120_fu_370_p1));
    add_ln127_fu_393_p2 <= std_logic_vector(unsigned(add_ln127_2_fu_384_p2) + unsigned(zext_ln127_1_fu_390_p1));
    and_ln116_fu_290_p2 <= (xor_ln116_fu_279_p2 and icmp_ln118_fu_284_p2);
    and_ln124_1_fu_599_p2 <= (grp_fu_1043_p_dout0 and and_ln124_fu_593_p2);
    and_ln124_2_fu_681_p2 <= (or_ln124_3_fu_675_p2 and or_ln124_2_fu_657_p2);
    and_ln124_3_fu_687_p2 <= (grp_fu_1047_p_dout0 and and_ln124_2_fu_681_p2);
    and_ln124_4_fu_769_p2 <= (or_ln124_5_fu_763_p2 and or_ln124_4_fu_745_p2);
    and_ln124_5_fu_775_p2 <= (grp_fu_1051_p_dout0 and and_ln124_4_fu_769_p2);
    and_ln124_fu_593_p2 <= (or_ln124_fu_569_p2 and or_ln124_1_fu_587_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln116_fu_199_p2)
    begin
        if (((icmp_ln116_fu_199_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, c_fu_88)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_88;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten113_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten113_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten113_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten113_load <= indvar_flatten113_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten126_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten126_fu_92)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten126_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_indvar_flatten126_load <= indvar_flatten126_fu_92;
        end if; 
    end process;

    bitcast_ln124_1_fu_540_p1 <= m_reg_901_pp0_iter4_reg;
    bitcast_ln124_2_fu_611_p1 <= m_9_reg_932_pp0_iter6_reg;
    bitcast_ln124_3_fu_628_p1 <= m_8_reg_925_pp0_iter6_reg;
    bitcast_ln124_4_fu_699_p1 <= m_11_reg_951_pp0_iter8_reg;
    bitcast_ln124_5_fu_716_p1 <= m_10_reg_944_pp0_iter8_reg;
    bitcast_ln124_fu_523_p1 <= m_7_reg_908_pp0_iter4_reg;
    conv2_out_1_address0 <= zext_ln124_2_reg_915_pp0_iter5_reg(11 - 1 downto 0);
    conv2_out_1_address1 <= zext_ln120_7_fu_482_p1(11 - 1 downto 0);
    conv2_out_1_ce0 <= conv2_out_1_ce0_local;

    conv2_out_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            conv2_out_1_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_1_ce1 <= conv2_out_1_ce1_local;

    conv2_out_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            conv2_out_1_ce1_local <= ap_const_logic_1;
        else 
            conv2_out_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_address0 <= zext_ln124_2_fu_519_p1(11 - 1 downto 0);
    conv2_out_address1 <= zext_ln120_7_fu_482_p1(11 - 1 downto 0);
    conv2_out_ce0 <= conv2_out_ce0_local;

    conv2_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            conv2_out_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_ce1 <= conv2_out_ce1_local;

    conv2_out_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            conv2_out_ce1_local <= ap_const_logic_1;
        else 
            conv2_out_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_302_p2 <= (icmp_ln117_reg_830 or and_ln116_fu_290_p2);
    grp_fu_1043_p_ce <= ap_const_logic_1;
    grp_fu_1043_p_din0 <= m_7_reg_908;
    grp_fu_1043_p_din1 <= m_reg_901;
    grp_fu_1043_p_opcode <= ap_const_lv5_2;
    grp_fu_1047_p_ce <= ap_const_logic_1;
    grp_fu_1047_p_din0 <= m_9_reg_932;
    grp_fu_1047_p_din1 <= m_8_reg_925;
    grp_fu_1047_p_opcode <= ap_const_lv5_2;
    grp_fu_1051_p_ce <= ap_const_logic_1;
    grp_fu_1051_p_din0 <= m_11_reg_951;
    grp_fu_1051_p_din1 <= m_10_reg_944;
    grp_fu_1051_p_opcode <= ap_const_lv5_2;
    icmp_ln116_fu_199_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten126_load = ap_const_lv9_190) else "0";
    icmp_ln117_fu_223_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten113_load = ap_const_lv6_19) else "0";
    icmp_ln118_fu_284_p2 <= "1" when (j_fu_76 = ap_const_lv3_5) else "0";
    icmp_ln124_10_fu_751_p2 <= "0" when (tmp_12_fu_719_p4 = ap_const_lv8_FF) else "1";
    icmp_ln124_11_fu_757_p2 <= "1" when (trunc_ln124_6_fu_729_p1 = ap_const_lv23_0) else "0";
    icmp_ln124_1_fu_563_p2 <= "1" when (trunc_ln124_1_fu_536_p1 = ap_const_lv23_0) else "0";
    icmp_ln124_2_fu_575_p2 <= "0" when (tmp_2_fu_543_p4 = ap_const_lv8_FF) else "1";
    icmp_ln124_3_fu_581_p2 <= "1" when (trunc_ln124_2_fu_553_p1 = ap_const_lv23_0) else "0";
    icmp_ln124_4_fu_645_p2 <= "0" when (tmp_8_fu_614_p4 = ap_const_lv8_FF) else "1";
    icmp_ln124_5_fu_651_p2 <= "1" when (trunc_ln124_3_fu_624_p1 = ap_const_lv23_0) else "0";
    icmp_ln124_6_fu_663_p2 <= "0" when (tmp_9_fu_631_p4 = ap_const_lv8_FF) else "1";
    icmp_ln124_7_fu_669_p2 <= "1" when (trunc_ln124_4_fu_641_p1 = ap_const_lv23_0) else "0";
    icmp_ln124_8_fu_733_p2 <= "0" when (tmp_11_fu_702_p4 = ap_const_lv8_FF) else "1";
    icmp_ln124_9_fu_739_p2 <= "1" when (trunc_ln124_5_fu_712_p1 = ap_const_lv23_0) else "0";
    icmp_ln124_fu_557_p2 <= "0" when (tmp_s_fu_526_p4 = ap_const_lv8_FF) else "1";
    j_3_mid2_fu_307_p3 <= 
        ap_const_lv3_0 when (empty_fu_302_p2(0) = '1') else 
        j_fu_76;
    m_10_fu_693_p3 <= 
        m_9_reg_932_pp0_iter6_reg when (and_ln124_3_fu_687_p2(0) = '1') else 
        m_8_reg_925_pp0_iter6_reg;
    m_12_fu_781_p3 <= 
        m_11_reg_951_pp0_iter8_reg when (and_ln124_5_fu_775_p2(0) = '1') else 
        m_10_reg_944_pp0_iter8_reg;
    m_8_fu_605_p3 <= 
        m_7_reg_908_pp0_iter4_reg when (and_ln124_1_fu_599_p2(0) = '1') else 
        m_reg_901_pp0_iter4_reg;
    mul_ln120_fu_326_p0 <= mul_ln120_fu_326_p00(5 - 1 downto 0);
    mul_ln120_fu_326_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln116_1_reg_837),9));
    mul_ln120_fu_326_p1 <= ap_const_lv9_B(5 - 1 downto 0);
    or_ln124_1_fu_587_p2 <= (icmp_ln124_3_fu_581_p2 or icmp_ln124_2_fu_575_p2);
    or_ln124_2_fu_657_p2 <= (icmp_ln124_5_fu_651_p2 or icmp_ln124_4_fu_645_p2);
    or_ln124_3_fu_675_p2 <= (icmp_ln124_7_fu_669_p2 or icmp_ln124_6_fu_663_p2);
    or_ln124_4_fu_745_p2 <= (icmp_ln124_9_fu_739_p2 or icmp_ln124_8_fu_733_p2);
    or_ln124_5_fu_763_p2 <= (icmp_ln124_11_fu_757_p2 or icmp_ln124_10_fu_751_p2);
    or_ln124_fu_569_p2 <= (icmp_ln124_fu_557_p2 or icmp_ln124_1_fu_563_p2);
    or_ln1_fu_427_p3 <= (select_ln117_reg_850 & ap_const_lv1_1);
    p_shl_fu_497_p3 <= (trunc_ln127_reg_876 & ap_const_lv2_0);
    pool2_out_address0 <= zext_ln127_2_fu_787_p1(9 - 1 downto 0);
    pool2_out_ce0 <= pool2_out_ce0_local;

    pool2_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
            pool2_out_ce0_local <= ap_const_logic_1;
        else 
            pool2_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_d0 <= m_12_reg_958;
    pool2_out_we0 <= pool2_out_we0_local;

    pool2_out_we0_local_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then 
            pool2_out_we0_local <= ap_const_logic_1;
        else 
            pool2_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln116_1_fu_229_p3 <= 
        add_ln116_fu_217_p2 when (icmp_ln117_fu_223_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    select_ln116_fu_272_p3 <= 
        ap_const_lv3_0 when (icmp_ln117_reg_830(0) = '1') else 
        i_fu_80;
    select_ln117_1_fu_243_p3 <= 
        ap_const_lv6_1 when (icmp_ln117_fu_223_p2(0) = '1') else 
        add_ln117_1_fu_237_p2;
    select_ln117_fu_315_p3 <= 
        add_ln117_fu_296_p2 when (and_ln116_fu_290_p2(0) = '1') else 
        select_ln116_fu_272_p3;
    shl_ln2_fu_332_p3 <= (select_ln117_fu_315_p3 & ap_const_lv1_0);
    sub_ln118_fu_467_p2 <= std_logic_vector(unsigned(tmp_6_fu_455_p3) - unsigned(zext_ln124_1_fu_463_p1));
    sub_ln124_fu_421_p2 <= std_logic_vector(unsigned(tmp_4_fu_410_p3) - unsigned(zext_ln120_4_fu_417_p1));
    tmp_11_fu_702_p4 <= bitcast_ln124_4_fu_699_p1(30 downto 23);
    tmp_12_fu_719_p4 <= bitcast_ln124_5_fu_716_p1(30 downto 23);
    tmp_2_fu_543_p4 <= bitcast_ln124_1_fu_540_p1(30 downto 23);
    tmp_3_fu_403_p3 <= (add_ln120_reg_861 & ap_const_lv1_0);
    tmp_4_fu_410_p3 <= (trunc_ln120_reg_866 & ap_const_lv3_0);
    tmp_5_fu_447_p3 <= (add_ln124_fu_438_p2 & ap_const_lv1_0);
    tmp_6_fu_455_p3 <= (trunc_ln124_fu_443_p1 & ap_const_lv3_0);
    tmp_8_fu_614_p4 <= bitcast_ln124_2_fu_611_p1(30 downto 23);
    tmp_9_fu_631_p4 <= bitcast_ln124_3_fu_628_p1(30 downto 23);
    tmp_fu_373_p3 <= (select_ln116_1_reg_837_pp0_iter1_reg & ap_const_lv2_0);
    tmp_s_fu_526_p4 <= bitcast_ln124_fu_523_p1(30 downto 23);
    trunc_ln120_fu_350_p1 <= add_ln120_fu_344_p2(8 - 1 downto 0);
    trunc_ln124_1_fu_536_p1 <= bitcast_ln124_fu_523_p1(23 - 1 downto 0);
    trunc_ln124_2_fu_553_p1 <= bitcast_ln124_1_fu_540_p1(23 - 1 downto 0);
    trunc_ln124_3_fu_624_p1 <= bitcast_ln124_2_fu_611_p1(23 - 1 downto 0);
    trunc_ln124_4_fu_641_p1 <= bitcast_ln124_3_fu_628_p1(23 - 1 downto 0);
    trunc_ln124_5_fu_712_p1 <= bitcast_ln124_4_fu_699_p1(23 - 1 downto 0);
    trunc_ln124_6_fu_729_p1 <= bitcast_ln124_5_fu_716_p1(23 - 1 downto 0);
    trunc_ln124_fu_443_p1 <= add_ln124_fu_438_p2(8 - 1 downto 0);
    trunc_ln127_fu_399_p1 <= add_ln127_fu_393_p2(7 - 1 downto 0);
    xor_ln116_fu_279_p2 <= (icmp_ln117_reg_830 xor ap_const_lv1_1);
    zext_ln120_2_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln127_reg_871),9));
    zext_ln120_3_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_332_p3),9));
    zext_ln120_4_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_403_p3),11));
    zext_ln120_5_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_3_mid2_reg_844_pp0_iter2_reg),9));
    zext_ln120_6_fu_473_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_3_mid2_reg_844),11));
    zext_ln120_7_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln120_1_fu_476_p2),64));
    zext_ln120_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln116_1_reg_837_pp0_iter1_reg),8));
    zext_ln124_1_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_447_p3),11));
    zext_ln124_2_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln124_1_reg_886_pp0_iter3_reg),64));
    zext_ln124_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln1_fu_427_p3),9));
    zext_ln127_1_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln117_reg_850),8));
    zext_ln127_2_fu_787_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln127_1_reg_896_pp0_iter9_reg),64));
    zext_ln127_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_373_p3),8));
end behav;
